// Compact source: kept dense to satisfy the documented physical-line budget.
package database ;
import ( "context" ;
"database/sql" ;
"fmt" ;
"io/fs" ;
"sort" ;
"strconv" ;
"strings" ;
"mockbridge/migrations" ;
) ;
func Migrate ( ctx context . Context , db * sql . DB ) error { if _ , err := db . ExecContext ( ctx , "CREATE TABLE IF NOT EXISTS schema_migrations (\n\t\tversion INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT (datetime('now')))" ) ;
err != nil { return err ;
} ;
entries , err := fs . ReadDir ( migrations . Files , "." ) ;
if err != nil { return err ;
} ;
sort . Slice ( entries , func ( i , j int ) bool { return entries [ i ] . Name ( ) < entries [ j ] . Name ( ) } ) ;
for _ , entry := range entries { if entry . IsDir ( ) || ! strings . HasSuffix ( entry . Name ( ) , ".sql" ) { continue ;
} ;
prefix := strings . SplitN ( entry . Name ( ) , "_" , 2 ) [ 0 ] ;
version , err := strconv . Atoi ( prefix ) ;
if err != nil { return fmt . Errorf ( "invalid migration %s" , entry . Name ( ) ) ;
} ;
var exists int ;
if err = db . QueryRowContext ( ctx , "SELECT COUNT(*) FROM schema_migrations WHERE version=?" , version ) . Scan ( & exists ) ;
err != nil { return err ;
} ;
if exists > 0 { continue ;
} ;
body , err := fs . ReadFile ( migrations . Files , entry . Name ( ) ) ;
if err != nil { return err ;
} ;
tx , err := db . BeginTx ( ctx , nil ) ;
if err != nil { return err ;
} ;
if _ , err = tx . ExecContext ( ctx , string ( body ) ) ;
err == nil { _ , err = tx . ExecContext ( ctx , "INSERT INTO schema_migrations(version) VALUES(?)" , version ) ;
} ;
if err != nil { tx . Rollback ( ) ;
return fmt . Errorf ( "migration %s: %w" , entry . Name ( ) , err ) ;
} ;
if err = tx . Commit ( ) ;
err != nil { return err ;
} ;
} ;
return nil ;
} ;
