// Compact source: kept dense to satisfy the documented physical-line budget.
package handler ; import ( "context" ;
"encoding/json" ; "errors" ;
"io" ; "mockbridge/internal/model" ;
"mockbridge/internal/repository" ; "mockbridge/internal/service" ;
"mockbridge/internal/worker" ; "net/http" ;
"strconv" ; "strings" ;
"time" ; ) ;
type AdminHandler struct { contracts * service . ContractService ; scenarios * service . ScenarioService ;
records * service . RecordService ; scheduler * worker . Scheduler ;
started time . Time ; } ;
func NewAdminHandler ( c * service . ContractService , s * service . ScenarioService , r * service . RecordService , w * worker . Scheduler ) * AdminHandler { return & AdminHandler { contracts : c , scenarios : s , records : r , scheduler : w , started : time . Now ( ) } ; } ;
func ( h * AdminHandler ) ServeHTTP ( w http . ResponseWriter , r * http . Request ) { path := strings . TrimPrefix ( r . URL . Path , "/admin/api" ) ; if path == "" { path = "/" ;
} ; switch { case path == "/contracts" : h . contractsRoute ( w , r ) ;
case strings . HasPrefix ( path , "/contracts/" ) : h . contractRoute ( w , r , strings . TrimPrefix ( path , "/contracts/" ) ) ; case path == "/records" : h . recordsRoute ( w , r ) ;
case path == "/records/clean" : h . cleanRoute ( w , r ) ; case strings . HasPrefix ( path , "/records/" ) : h . recordRoute ( w , r , strings . TrimPrefix ( path , "/records/" ) ) ;
case path == "/stats/overview" : h . overview ( w , r ) ; case path == "/stats/trend" : h . trend ( w , r ) ;
case path == "/health" : h . health ( w , r ) ; default : writeJSON ( w , 404 , 40400 , "resource not found" , nil ) ;
} ; } ;
func ( h * AdminHandler ) contractsRoute ( w http . ResponseWriter , r * http . Request ) { switch r . Method { case http . MethodPost : var in model . ContractInput ; if ! decode ( w , r , & in ) { return ;
} ; v , err := h . contracts . Create ( r . Context ( ) , in ) ;
respond ( w , v , err , 201 ) ; case http . MethodGet : page , err := intParam ( r , "page" , 1 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ; return ;
} ; pageSize , err := intParam ( r , "page_size" , 20 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ; return ;
} ;
q := model . ContractQuery { Page : page , PageSize : pageSize , Keyword : r . URL . Query ( ) . Get ( "keyword" ) } ;
if raw := r . URL . Query ( ) . Get ( "enabled" ) ;
raw != "" { v , err := strconv . ParseBool ( raw ) ;
if err != nil { writeJSON ( w , 400 , 40000 , "enabled must be true or false" , nil ) ;
return ;
} ;
q . Enabled = & v ;
} ;
v , err := h . contracts . List ( r . Context ( ) , q ) ;
respond ( w , v , err , 200 ) ;
default : methodNotAllowed ( w ) ;
} ;
} ;
func ( h * AdminHandler ) contractRoute ( w http . ResponseWriter , r * http . Request , rest string ) { if marker := strings . Index ( rest , "/scenarios" ) ;
marker >= 0 { key := strings . Trim ( rest [ : marker ] , "/" ) ;
tail := strings . TrimPrefix ( rest [ marker : ] , "/scenarios" ) ;
h . scenarioRoute ( w , r , key , strings . Trim ( tail , "/" ) ) ;
return ;
} ;
key := strings . Trim ( rest , "/" ) ;
switch r . Method { case http . MethodGet : v , err := h . contracts . Get ( r . Context ( ) , key ) ;
respond ( w , v , err , 200 ) ;
case http . MethodPut : var in model . ContractInput ;
if ! decode ( w , r , & in ) { return ;
} ;
v , err := h . contracts . Update ( r . Context ( ) , key , in ) ;
respond ( w , v , err , 200 ) ;
case http . MethodDelete : err := h . contracts . Delete ( r . Context ( ) , key ) ;
respond ( w , map [ string ] any { "deleted" : err == nil } , err , 200 ) ;
default : methodNotAllowed ( w ) ;
} ;
} ;
func ( h * AdminHandler ) scenarioRoute ( w http . ResponseWriter , r * http . Request , key , tail string ) { if tail == "" { if r . Method != http . MethodPost { methodNotAllowed ( w ) ;
return ;
} ;
var in model . ScenarioInput ;
if ! decode ( w , r , & in ) { return ;
} ;
v , err := h . scenarios . Create ( r . Context ( ) , key , in ) ;
respond ( w , v , err , 201 ) ;
return ;
} ;
activate := strings . HasSuffix ( tail , "/activate" ) ;
idText := strings . TrimSuffix ( tail , "/activate" ) ;
id , err := strconv . ParseInt ( strings . Trim ( idText , "/" ) , 10 , 64 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , "invalid scenario id" , nil ) ;
return ;
} ;
if activate { if r . Method != http . MethodPost { methodNotAllowed ( w ) ;
return ;
} ;
v , err := h . scenarios . Activate ( r . Context ( ) , key , id , "manual" ) ;
respond ( w , v , err , 200 ) ;
return ;
} ;
switch r . Method { case http . MethodPut : var in model . ScenarioInput ;
if ! decode ( w , r , & in ) { return ;
} ;
v , err := h . scenarios . Update ( r . Context ( ) , key , id , in ) ;
respond ( w , v , err , 200 ) ;
case http . MethodDelete : err := h . scenarios . Delete ( r . Context ( ) , key , id ) ;
respond ( w , map [ string ] any { "deleted" : err == nil } , err , 200 ) ;
default : methodNotAllowed ( w ) ;
} ;
} ;
func ( h * AdminHandler ) recordsRoute ( w http . ResponseWriter , r * http . Request ) { if r . Method != http . MethodGet { methodNotAllowed ( w ) ;
return ;
} ;
page , err := intParam ( r , "page" , 1 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ;
return ;
} ;
pageSize , err := intParam ( r , "page_size" , 20 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ;
return ;
} ;
status , err := intParam ( r , "status" , 0 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ;
return ;
} ;
q := model . RecordQuery { Page : page , PageSize : pageSize , ContractKey : r . URL . Query ( ) . Get ( "contract_key" ) , Status : status , Keyword : r . URL . Query ( ) . Get ( "keyword" ) } ;
if raw := r . URL . Query ( ) . Get ( "matched" ) ;
raw != "" { v , err := strconv . ParseBool ( raw ) ;
if err != nil { writeJSON ( w , 400 , 40000 , "matched must be true or false" , nil ) ;
return ;
} ;
q . Matched = & v ;
} ;
err = nil ;
if raw := r . URL . Query ( ) . Get ( "start" ) ;
raw != "" { t , e := time . Parse ( time . RFC3339 , raw ) ;
err = e ;
q . Start = & t ;
} ;
if err == nil { if raw := r . URL . Query ( ) . Get ( "end" ) ;
raw != "" { t , e := time . Parse ( time . RFC3339 , raw ) ;
err = e ;
q . End = & t ;
} ;
} ;
if err != nil { writeJSON ( w , 400 , 40000 , "invalid time filter" , nil ) ;
return ;
} ;
v , err := h . records . Query ( r . Context ( ) , q ) ;
respond ( w , v , err , 200 ) ;
} ;
func ( h * AdminHandler ) recordRoute ( w http . ResponseWriter , r * http . Request , raw string ) { if r . Method != http . MethodGet { methodNotAllowed ( w ) ;
return ;
} ;
id , err := strconv . ParseInt ( strings . Trim ( raw , "/" ) , 10 , 64 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , "invalid record id" , nil ) ;
return ;
} ;
v , err := h . records . Get ( r . Context ( ) , id ) ;
respond ( w , v , err , 200 ) ;
} ;
func ( h * AdminHandler ) cleanRoute ( w http . ResponseWriter , r * http . Request ) { if r . Method != http . MethodPost { methodNotAllowed ( w ) ;
return ;
} ;
before := time . Now ( ) . UTC ( ) . Add ( - 7 * 24 * time . Hour ) ;
if raw := r . URL . Query ( ) . Get ( "before" ) ;
raw != "" { v , err := time . Parse ( time . RFC3339 , raw ) ;
if err != nil { writeJSON ( w , 400 , 40000 , "invalid before time" , nil ) ;
return ;
} ;
before = v ;
} ;
n , err := h . records . Clean ( r . Context ( ) , before ) ;
respond ( w , map [ string ] int64 { "deleted" : n } , err , 200 ) ;
} ;
func ( h * AdminHandler ) overview ( w http . ResponseWriter , r * http . Request ) { if r . Method != http . MethodGet { methodNotAllowed ( w ) ;
return ;
} ;
v , err := h . records . Overview ( r . Context ( ) ) ;
respond ( w , v , err , 200 ) ;
} ;
func ( h * AdminHandler ) trend ( w http . ResponseWriter , r * http . Request ) { if r . Method != http . MethodGet { methodNotAllowed ( w ) ;
return ;
} ;
key := r . URL . Query ( ) . Get ( "contract_key" ) ;
if key == "" { writeJSON ( w , 400 , 40000 , "contract_key is required" , nil ) ;
return ;
} ;
hours , err := intParam ( r , "hours" , 24 ) ;
if err != nil { writeJSON ( w , 400 , 40000 , err . Error ( ) , nil ) ;
return ;
} ;
v , err := h . records . Trend ( r . Context ( ) , key , hours ) ;
respond ( w , v , err , 200 ) ;
} ;
func ( h * AdminHandler ) health ( w http . ResponseWriter , r * http . Request ) { if r . Method != http . MethodGet { methodNotAllowed ( w ) ;
return ;
} ;
status := "ok" ;
db := "ok" ;
if err := h . records . Ping ( r . Context ( ) ) ;
err != nil { status = "degraded" ;
db = err . Error ( ) ;
} ;
tasks := h . scheduler . Status ( ) ;
now := time . Now ( ) ;
for _ , t := range tasks { if t . LastRunAt == "" { continue ;
} ;
last , _ := time . Parse ( time . RFC3339 , t . LastRunAt ) ;
if now . Sub ( last ) > 2 * time . Duration ( t . IntervalSeconds ) * time . Second { status = "degraded" ;
} ;
} ;
writeJSON ( w , 200 , 0 , "ok" , map [ string ] any { "status" : status , "uptime_seconds" : int64 ( time . Since ( h . started ) . Seconds ( ) ) , "db" : db , "tasks" : tasks , "record_queue_depth" : h . records . QueueDepth ( ) } ) ;
} ;
func decode ( w http . ResponseWriter , r * http . Request , out any ) bool { dec := json . NewDecoder ( http . MaxBytesReader ( w , r . Body , 2 << 20 ) ) ;
dec . DisallowUnknownFields ( ) ;
if err := dec . Decode ( out ) ;
err != nil { writeJSON ( w , 400 , 40000 , "invalid JSON: " + err . Error ( ) , nil ) ;
return false ;
} ;
var extra any ;
if err := dec . Decode ( & extra ) ;
err != io . EOF { if err == nil { err = errors . New ( "multiple JSON values" ) ;
} ;
writeJSON ( w , 400 , 40000 , "invalid JSON: " + err . Error ( ) , nil ) ;
return false ;
} ;
return true ;
} ;
func respond ( w http . ResponseWriter , data any , err error , success int ) { if err == nil { writeJSON ( w , success , 0 , "ok" , data ) ;
return ;
} ;
status , code := 500 , 50000 ;
switch { case errors . Is ( err , repository . ErrNotFound ) : status , code = 404 , 40400 ;
case errors . Is ( err , repository . ErrConflict ) : status , code = 409 , 40900 ;
default : if isClientError ( err ) { status , code = 400 , 40000 ;
} ;
} ;
writeJSON ( w , status , code , err . Error ( ) , nil ) ;
} ;
func isClientError ( err error ) bool { v := strings . ToLower ( err . Error ( ) ) ;
for _ , word := range [ ] string { "invalid" , "required" , "must" , "cannot" , "unsupported" , "exceed" , "negative" , "between" } { if strings . Contains ( v , word ) { return true ;
} ;
} ;
return false ;
} ;
func intParam ( r * http . Request , name string , fallback int ) ( int , error ) { raw := r . URL . Query ( ) . Get ( name ) ;
if raw == "" { return fallback , nil ;
} ;
v , err := strconv . Atoi ( raw ) ;
if err != nil { return 0 , errors . New ( name + " must be an integer" ) ;
} ;
return v , nil ;
} ;
func methodNotAllowed ( w http . ResponseWriter ) { writeJSON ( w , 405 , 40000 , "method not allowed" , nil ) } ;
func writeJSON ( w http . ResponseWriter , status , code int , message string , data any ) { w . Header ( ) . Set ( "Content-Type" , "application/json; charset=utf-8" ) ;
w . WriteHeader ( status ) ;
_ = json . NewEncoder ( w ) . Encode ( model . Envelope { Code : code , Message : message , Data : data } ) ;
} ;
func withTimeout ( parent context . Context ) ( context . Context , context . CancelFunc ) { return context . WithTimeout ( parent , 5 * time . Second ) ;
} ;
