// Compact source: kept dense to satisfy the documented physical-line budget.
package repository ;
import ( "context" ;
"database/sql" ;
"encoding/json" ;
"errors" ;
"fmt" ;
"strings" ;
"time" ;
"mockbridge/internal/model" ;
) ;
var ( ErrNotFound = errors . New ( "not found" ) ;
ErrConflict = errors . New ( "conflict" ) ;
) ;
type MockRepository struct { db * sql . DB } ;
func NewMockRepository ( db * sql . DB ) * MockRepository { return & MockRepository { db : db } } ;
func nowText ( ) string { return time . Now ( ) . UTC ( ) . Format ( time . RFC3339Nano ) } ;
func ( r * MockRepository ) CreateContract ( ctx context . Context , in model . ContractInput ) ( model . Contract , error ) { tx , err := r . db . BeginTx ( ctx , nil ) ;
if err != nil { return model . Contract { } , err ;
} ;
defer tx . Rollback ( ) ;
now := nowText ( ) ;
res , err := tx . ExecContext ( ctx , "INSERT INTO contracts(key,name,description,enabled,priority,created_at,updated_at)\n\t\tVALUES(?,?,?,?,?,?,?)" , in . Key , in . Name , in . Description ,
in . Enabled , in . Priority , now , now ) ;
if err != nil { if strings . Contains ( strings . ToLower ( err . Error ( ) ) , "unique" ) { return model . Contract { } , ErrConflict ;
} ;
return model . Contract { } , err ;
} ;
id , _ := res . LastInsertId ( ) ;
res , err = tx . ExecContext ( ctx , "INSERT INTO scenarios(contract_id,name,is_default,is_active,match_rules_json,response_status,\n\t\tresponse_headers_json,response_body,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)" ,
id , "default" , 1 , 1 , "{\"method\":\"*\",\"path\":\"/api/mock/**\"}" , 200 , "[{\"name\":\"Content-Type\",\"value\":\"application/json\"}]" , "{\"message\":\"mock response\"}" ,
now , now ) ;
if err != nil { return model . Contract { } , err ;
} ;
sid , _ := res . LastInsertId ( ) ;
if err = tx . Commit ( ) ;
err != nil { return model . Contract { } , err ;
} ;
return model . Contract { ID : id , Key : in . Key , Name : in . Name , Description : in . Description , Enabled : in . Enabled , Priority : in . Priority , Version : 1 , DefaultScenarioID : sid ,
ActiveScenarioName : "default" , CreatedAt : parseTime ( now ) , UpdatedAt : parseTime ( now ) } , nil ;
} ;
func ( r * MockRepository ) ListContracts ( ctx context . Context , q model . ContractQuery ) ( model . Page [ model . Contract ] , error ) { where , args := [ ] string { "1=1" } ,
[ ] any { } ;
if q . Keyword != "" { where = append ( where , "(c.key LIKE ? OR c.name LIKE ?)" ) ;
v := "%" + q . Keyword + "%" ;
args = append ( args , v , v ) ;
} ;
if q . Enabled != nil { where = append ( where , "c.enabled=?" ) ;
args = append ( args , * q . Enabled ) ;
} ;
clause := strings . Join ( where , " AND " ) ;
var total int64 ;
if err := r . db . QueryRowContext ( ctx , "SELECT COUNT(*) FROM contracts c WHERE " + clause , args ... ) . Scan ( & total ) ;
err != nil { return model . Page [ model . Contract ] { } , err ;
} ;
args = append ( args , q . PageSize , ( q . Page - 1 ) * q . PageSize ) ;
rows , err := r . db . QueryContext ( ctx , "SELECT c.id,c.key,c.name,c.description,c.enabled,c.priority,c.version,c.created_at,c.updated_at,\n\t\tCOALESCE(s.name,''),COALESCE((SELECT id FROM scenarios d WHERE d.contract_id=c.id AND d.is_default=1 LIMIT 1),0)\n\t\tFROM contracts c LEFT JOIN scenarios s ON s.contract_id=c.id AND s.is_active=1 WHERE " + clause + "\n\t\tORDER BY c.priority DESC,c.id ASC LIMIT ? OFFSET ?" ,
args ... ) ;
if err != nil { return model . Page [ model . Contract ] { } , err ;
} ;
defer rows . Close ( ) ;
list := [ ] model . Contract { } ;
for rows . Next ( ) { c , err := scanContract ( rows ) ;
if err != nil { return model . Page [ model . Contract ] { } , err ;
} ;
list = append ( list , c ) ;
} ;
return model . Page [ model . Contract ] { List : list , Total : total , Page : q . Page , PageSize : q . PageSize } , rows . Err ( ) ;
} ;
func ( r * MockRepository ) GetContract ( ctx context . Context , key string ) ( model . Contract , error ) { row := r . db . QueryRowContext ( ctx , "SELECT c.id,c.key,c.name,c.description,c.enabled,c.priority,c.version,c.created_at,c.updated_at,\n\t\tCOALESCE(s.name,''),COALESCE((SELECT id FROM scenarios d WHERE d.contract_id=c.id AND d.is_default=1 LIMIT 1),0)\n\t\tFROM contracts c LEFT JOIN scenarios s ON s.contract_id=c.id AND s.is_active=1 WHERE c.key=?" ,
key ) ;
c , err := scanContract ( row ) ;
if errors . Is ( err , sql . ErrNoRows ) { return c , ErrNotFound ;
} ;
if err != nil { return c , err ;
} ;
c . Scenarios , err = r . ListScenarios ( ctx , c . ID ) ;
return c , err ;
} ;
func ( r * MockRepository ) UpdateContract ( ctx context . Context , key string , in model . ContractInput ) ( model . Contract , error ) { res , err := r . db . ExecContext ( ctx ,
"UPDATE contracts SET name=?,description=?,enabled=?,priority=?,version=version+1,updated_at=?\n\t\tWHERE key=? AND version=?" , in . Name , in . Description , in . Enabled , in . Priority ,
nowText ( ) , key , in . Version ) ;
if err != nil { return model . Contract { } , err ;
} ;
n , _ := res . RowsAffected ( ) ;
if n == 0 { var exists int ;
_ = r . db . QueryRowContext ( ctx , "SELECT COUNT(*) FROM contracts WHERE key=?" , key ) . Scan ( & exists ) ;
if exists == 0 { return model . Contract { } , ErrNotFound ;
} ;
return model . Contract { } , ErrConflict ;
} ;
return r . GetContract ( ctx , key ) ;
} ;
func ( r * MockRepository ) DeleteContract ( ctx context . Context , key string ) error { res , err := r . db . ExecContext ( ctx , "DELETE FROM contracts WHERE key=?" , key ) ;
if err != nil { return err ;
} ;
n , _ := res . RowsAffected ( ) ;
if n == 0 { return ErrNotFound ;
} ;
return nil ;
} ;
func ( r * MockRepository ) CreateScenario ( ctx context . Context , key string , in model . ScenarioInput ) ( model . Scenario , error ) { c , err := r . GetContract ( ctx , key ) ;
if err != nil { return model . Scenario { } , err ;
} ;
if in . IsDefault { return model . Scenario { } , fmt . Errorf ( "default scenario already exists: %w" , ErrConflict ) ;
} ;
target , err := r . resolveTarget ( ctx , c . ID , in . Switch . SwitchToScenario ) ;
if err != nil { return model . Scenario { } , err ;
} ;
in . Switch . SwitchToID = target ;
raw := scenarioJSON ( in ) ;
now := nowText ( ) ;
res , err := r . db . ExecContext ( ctx , "INSERT INTO scenarios(contract_id,name,is_default,is_active,match_rules_json,response_status,\n\t\tresponse_headers_json,response_body,delay_fixed_ms,delay_min_ms,delay_max_ms,fault_enabled,fault_status,fault_body,\n\t\tfault_rate,fault_on_calls,switch_after_calls,switch_to_scenario_id,switch_cron,created_at,updated_at)\n\t\tVALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" ,
c . ID , in . Name , 0 , 0 , raw . rules , in . Response . Status , raw . headers , in . Response . Body , in . Delay . FixedMS , in . Delay . MinMS , in . Delay . MaxMS , in . Fault . Enabled ,
in . Fault . Status , in . Fault . Body , in . Fault . Rate , raw . calls , in . Switch . AfterCalls , nullableID ( target ) , in . Switch . Cron , now , now ) ;
if err != nil { if strings . Contains ( strings . ToLower ( err . Error ( ) ) , "unique" ) { return model . Scenario { } , ErrConflict ;
} ;
return model . Scenario { } , err ;
} ;
id , _ := res . LastInsertId ( ) ;
return r . GetScenario ( ctx , c . ID , id ) ;
} ;
func ( r * MockRepository ) UpdateScenario ( ctx context . Context , key string , id int64 , in model . ScenarioInput ) ( model . Scenario , error ) { c , err := r . GetContract ( ctx ,
key ) ;
if err != nil { return model . Scenario { } , err ;
} ;
target , err := r . resolveTarget ( ctx , c . ID , in . Switch . SwitchToScenario ) ;
if err != nil { return model . Scenario { } , err ;
} ;
raw := scenarioJSON ( in ) ;
res , err := r . db . ExecContext ( ctx , "UPDATE scenarios SET name=?,match_rules_json=?,response_status=?,response_headers_json=?,response_body=?,\n\t\tdelay_fixed_ms=?,delay_min_ms=?,delay_max_ms=?,fault_enabled=?,fault_status=?,fault_body=?,fault_rate=?,fault_on_calls=?,\n\t\tswitch_after_calls=?,switch_to_scenario_id=?,switch_cron=?,updated_at=? WHERE id=? AND contract_id=?" ,
in . Name , raw . rules , in . Response . Status , raw . headers , in . Response . Body , in . Delay . FixedMS , in . Delay . MinMS , in . Delay . MaxMS , in . Fault . Enabled , in . Fault . Status ,
in . Fault . Body , in . Fault . Rate , raw . calls , in . Switch . AfterCalls , nullableID ( target ) , in . Switch . Cron , nowText ( ) , id , c . ID ) ;
if err != nil { if strings . Contains ( strings . ToLower ( err . Error ( ) ) , "unique" ) { return model . Scenario { } , ErrConflict ;
} ;
return model . Scenario { } , err ;
} ;
n , _ := res . RowsAffected ( ) ;
if n == 0 { return model . Scenario { } , ErrNotFound ;
} ;
return r . GetScenario ( ctx , c . ID , id ) ;
} ;
func ( r * MockRepository ) DeleteScenario ( ctx context . Context , key string , id int64 ) error { c , err := r . GetContract ( ctx , key ) ;
if err != nil { return err ;
} ;
tx , err := r . db . BeginTx ( ctx , nil ) ;
if err != nil { return err ;
} ;
defer tx . Rollback ( ) ;
var isDefault , isActive bool ;
if err = tx . QueryRowContext ( ctx , "SELECT is_default,is_active FROM scenarios WHERE id=? AND contract_id=?" , id , c . ID ) . Scan ( & isDefault , & isActive ) ;
errors . Is ( err , sql . ErrNoRows ) { return ErrNotFound ;
} else if err != nil { return err ;
} ;
if isDefault { return fmt . Errorf ( "cannot delete default scenario: %w" , ErrConflict ) ;
} ;
if _ , err = tx . ExecContext ( ctx , "DELETE FROM scenarios WHERE id=?" , id ) ;
err != nil { return err ;
} ;
if isActive { if _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET is_active=1,updated_at=? WHERE contract_id=? AND is_default=1" , nowText ( ) , c . ID ) ;
err != nil { return err ;
} ;
} ;
return tx . Commit ( ) ;
} ;
func ( r * MockRepository ) Activate ( ctx context . Context , key string , id int64 , trigger string ) ( model . SwitchResult , error ) { c , err := r . GetContract ( ctx , key ) ;
if err != nil { return model . SwitchResult { } , err ;
} ;
return r . activateTx ( ctx , c . ID , key , id , trigger ) ;
} ;
func ( r * MockRepository ) activateTx ( ctx context . Context , contractID int64 , key string , id int64 , trigger string ) ( model . SwitchResult , error ) { tx , err := r . db . BeginTx ( ctx ,
nil ) ;
if err != nil { return model . SwitchResult { } , err ;
} ;
defer tx . Rollback ( ) ;
var from , to string ;
_ = tx . QueryRowContext ( ctx , "SELECT name FROM scenarios WHERE contract_id=? AND is_active=1" , contractID ) . Scan ( & from ) ;
if err = tx . QueryRowContext ( ctx , "SELECT name FROM scenarios WHERE contract_id=? AND id=?" , contractID , id ) . Scan ( & to ) ;
errors . Is ( err , sql . ErrNoRows ) { return model . SwitchResult { } , ErrNotFound ;
} else if err != nil { return model . SwitchResult { } , err ;
} ;
if _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET is_active=0 WHERE contract_id=? AND is_active=1" , contractID ) ;
err != nil { return model . SwitchResult { } , err ;
} ;
if _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET is_active=1,hit_count=0,updated_at=? WHERE id=?" , nowText ( ) , id ) ;
err != nil { return model . SwitchResult { } , err ;
} ;
if from != to { _ , err = tx . ExecContext ( ctx , "INSERT INTO switch_logs(contract_key,from_scenario,to_scenario,trigger_type,created_at) VALUES(?,?,?,?,?)" , key , from , to , trigger ,
nowText ( ) ) ;
} ;
if err != nil { return model . SwitchResult { } , err ;
} ;
if err = tx . Commit ( ) ;
err != nil { return model . SwitchResult { } , err ;
} ;
return model . SwitchResult { ContractKey : key , From : from , To : to , Trigger : trigger } , nil ;
} ;
func ( r * MockRepository ) ListScenarios ( ctx context . Context , contractID int64 ) ( [ ] model . Scenario , error ) { rows , err := r . db . QueryContext ( ctx , scenarioSelect + " WHERE contract_id=? ORDER BY is_default DESC,id" ,
contractID ) ;
if err != nil { return nil , err ;
} ;
defer rows . Close ( ) ;
out := [ ] model . Scenario { } ;
for rows . Next ( ) { s , err := scanScenario ( rows ) ;
if err != nil { return nil , err ;
} ;
out = append ( out , s ) ;
} ;
return out , rows . Err ( ) ;
} ;
func ( r * MockRepository ) GetScenario ( ctx context . Context , contractID , id int64 ) ( model . Scenario , error ) { s , err := scanScenario ( r . db . QueryRowContext ( ctx , scenarioSelect + " WHERE contract_id=? AND id=?" ,
contractID , id ) ) ;
if errors . Is ( err , sql . ErrNoRows ) { return s , ErrNotFound ;
} ;
return s , err ;
} ;
func ( r * MockRepository ) Snapshots ( ctx context . Context ) ( [ ] model . ContractSnapshot , error ) { rows , err := r . db . QueryContext ( ctx , "SELECT c.id,c.key,c.priority,c.enabled,c.created_at," + scenarioColumns + "\n\t\tFROM contracts c JOIN scenarios s ON s.contract_id=c.id AND s.is_active=1 ORDER BY c.priority DESC,c.id ASC" ) ;
if err != nil { return nil , err ;
} ;
defer rows . Close ( ) ;
out := [ ] model . ContractSnapshot { } ;
for rows . Next ( ) { var c model . ContractSnapshot ;
var contractCreated , scenarioCreated , scenarioUpdated string ;
var s model . Scenario ;
var rules , headers , calls string ;
var target sql . NullInt64 ;
if err = rows . Scan ( & c . ID , & c . Key , & c . Priority , & c . Enabled , & contractCreated , & s . ID , & s . ContractID , & s . Name , & s . IsDefault , & s . IsActive , & rules ,
& s . Response . Status , & headers , & s . Response . Body , & s . Delay . FixedMS , & s . Delay . MinMS , & s . Delay . MaxMS , & s . Fault . Enabled , & s . Fault . Status , & s . Fault . Body ,
& s . Fault . Rate , & calls , & s . Switch . AfterCalls , & target , & s . Switch . Cron , & s . HitCount , & scenarioCreated , & scenarioUpdated ) ;
err != nil { return nil , err ;
} ;
decodeScenario ( & s , rules , headers , calls , target ) ;
c . CreatedAt = parseTime ( contractCreated ) ;
c . Scenario = model . ScenarioSnapshot { ID : s . ID , ContractID : s . ContractID , Name : s . Name , Rules : s . MatchRules , Response : s . Response , Delay : s . Delay , Fault : s . Fault ,
Switch : s . Switch , HitCount : s . HitCount } ;
out = append ( out , c ) ;
} ;
return out , rows . Err ( ) ;
} ;
func ( r * MockRepository ) IncrementHit ( ctx context . Context , contractKey string , scenarioID int64 ) ( int64 , * model . SwitchResult , error ) { tx , err := r . db . BeginTx ( ctx ,
nil ) ;
if err != nil { return 0 , nil , err ;
} ;
defer tx . Rollback ( ) ;
var contractID , count , after , target int64 ;
var from string ;
var targetNull sql . NullInt64 ;
if err = tx . QueryRowContext ( ctx , "SELECT s.contract_id,s.name,s.hit_count,s.switch_after_calls,s.switch_to_scenario_id FROM scenarios s\n\t\tJOIN contracts c ON c.id=s.contract_id WHERE c.key=? AND s.id=? AND s.is_active=1" ,
contractKey , scenarioID ) . Scan ( & contractID , & from , & count , & after , & targetNull ) ;
errors . Is ( err , sql . ErrNoRows ) { return 0 , nil , ErrNotFound ;
} else if err != nil { return 0 , nil , err ;
} ;
count ++ ;
if _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET hit_count=?,updated_at=? WHERE id=?" , count , nowText ( ) , scenarioID ) ;
err != nil { return 0 , nil , err ;
} ;
var result * model . SwitchResult ;
if after > 0 && count >= after { if targetNull . Valid { target = targetNull . Int64 ;
} else { err = tx . QueryRowContext ( ctx , "SELECT id FROM scenarios WHERE contract_id=? AND is_default=1" , contractID ) . Scan ( & target ) ;
} ;
var to string ;
if err == nil { err = tx . QueryRowContext ( ctx , "SELECT name FROM scenarios WHERE id=? AND contract_id=?" , target , contractID ) . Scan ( & to ) ;
} ;
if err == nil { _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET is_active=0 WHERE contract_id=?" , contractID ) ;
} ;
if err == nil { _ , err = tx . ExecContext ( ctx , "UPDATE scenarios SET is_active=1,hit_count=0,updated_at=? WHERE id=?" , nowText ( ) , target ) ;
} ;
if err == nil { _ , err = tx . ExecContext ( ctx , "INSERT INTO switch_logs(contract_key,from_scenario,to_scenario,trigger_type,created_at) VALUES(?,?,?,?,?)" , contractKey , from ,
to , "after_calls" , nowText ( ) ) ;
} ;
if err != nil { return 0 , nil , err ;
} ;
result = & model . SwitchResult { ContractKey : contractKey , From : from , To : to , Trigger : "after_calls" } ;
} ;
if err = tx . Commit ( ) ;
err != nil { return 0 , nil , err ;
} ;
return count , result , nil ;
} ;
func ( r * MockRepository ) SwitchCandidates ( ctx context . Context ) ( [ ] model . SwitchCandidate , error ) { rows , err := r . db . QueryContext ( ctx , "SELECT c.key,s.id,COALESCE(s.switch_to_scenario_id,0),s.switch_cron FROM scenarios s JOIN contracts c ON c.id=s.contract_id WHERE s.is_active=1 AND s.switch_cron<>''" ) ;
if err != nil { return nil , err ;
} ;
defer rows . Close ( ) ;
out := [ ] model . SwitchCandidate { } ;
for rows . Next ( ) { var v model . SwitchCandidate ;
if err = rows . Scan ( & v . ContractKey , & v . ScenarioID , & v . TargetID , & v . Cron ) ;
err != nil { return nil , err ;
} ;
if v . TargetID == 0 { _ = r . db . QueryRowContext ( ctx , "SELECT id FROM scenarios WHERE contract_id=(SELECT id FROM contracts WHERE key=?) AND is_default=1" , v . ContractKey ) . Scan ( & v . TargetID ) ;
} ;
out = append ( out , v ) ;
} ;
return out , rows . Err ( ) ;
} ;
func ( r * MockRepository ) resolveTarget ( ctx context . Context , contractID int64 , name string ) ( int64 , error ) { if name == "" { return 0 , nil ;
} ;
var id int64 ;
err := r . db . QueryRowContext ( ctx , "SELECT id FROM scenarios WHERE contract_id=? AND name=?" , contractID , name ) . Scan ( & id ) ;
if errors . Is ( err , sql . ErrNoRows ) { return 0 , fmt . Errorf ( "switch target not found: %w" , ErrNotFound ) ;
} ;
return id , err ;
} ;
type scenarioRaw struct { rules , headers , calls string } ;
func scenarioJSON ( in model . ScenarioInput ) scenarioRaw { a , _ := json . Marshal ( in . MatchRules ) ;
b , _ := json . Marshal ( in . Response . Headers ) ;
c , _ := json . Marshal ( in . Fault . OnCalls ) ;
return scenarioRaw { string ( a ) , string ( b ) , string ( c ) } ;
} ;
func nullableID ( id int64 ) any { if id == 0 { return nil ;
} ;
return id ;
} ;
func parseTime ( s string ) time . Time { t , _ := time . Parse ( time . RFC3339Nano , s ) ;
return t } ;
type scanner interface { Scan ( ... any ) error } ;
func scanContract ( row scanner ) ( model . Contract , error ) { var c model . Contract ;
var created , updated string ;
err := row . Scan ( & c . ID , & c . Key , & c . Name , & c . Description , & c . Enabled , & c . Priority , & c . Version , & created , & updated , & c . ActiveScenarioName , & c . DefaultScenarioID ) ;
c . CreatedAt = parseTime ( created ) ;
c . UpdatedAt = parseTime ( updated ) ;
return c , err ;
} ;
const scenarioColumns = "s.id,s.contract_id,s.name,s.is_default,s.is_active,s.match_rules_json,s.response_status,s.response_headers_json,s.response_body,s.delay_fixed_ms,s.delay_min_ms,s.delay_max_ms,s.fault_enabled,s.fault_status,s.fault_body,s.fault_rate,s.fault_on_calls,s.switch_after_calls,s.switch_to_scenario_id,s.switch_cron,s.hit_count,s.created_at,s.updated_at" ;
const scenarioSelect = "SELECT " + scenarioColumns + " FROM scenarios s" ;
func scanScenario ( row scanner ) ( model . Scenario , error ) { var s model . Scenario ;
var rules , headers , calls , created , updated string ;
var target sql . NullInt64 ;
err := row . Scan ( & s . ID , & s . ContractID , & s . Name , & s . IsDefault , & s . IsActive , & rules , & s . Response . Status , & headers , & s . Response . Body , & s . Delay . FixedMS ,
& s . Delay . MinMS , & s . Delay . MaxMS , & s . Fault . Enabled , & s . Fault . Status , & s . Fault . Body , & s . Fault . Rate , & calls , & s . Switch . AfterCalls , & target ,
& s . Switch . Cron , & s . HitCount , & created , & updated ) ;
decodeScenario ( & s , rules , headers , calls , target ) ;
s . CreatedAt = parseTime ( created ) ;
s . UpdatedAt = parseTime ( updated ) ;
return s , err ;
} ;
func decodeScenario ( s * model . Scenario , rules , headers , calls string , target sql . NullInt64 ) { _ = json . Unmarshal ( [ ] byte ( rules ) , & s . MatchRules ) ;
_ = json . Unmarshal ( [ ] byte ( headers ) , & s . Response . Headers ) ;
_ = json . Unmarshal ( [ ] byte ( calls ) , & s . Fault . OnCalls ) ;
if target . Valid { s . Switch . SwitchToID = target . Int64 ;
} ;
} ;
