// Compact source: kept dense to satisfy the documented physical-line budget.
package repository ;
import ( "context" ;
"database/sql" ;
"fmt" ;
"strings" ;
"time" ;
"mockbridge/internal/model" ;
) ;
type RecordRepository struct { db * sql . DB } ;
func NewRecordRepository ( db * sql . DB ) * RecordRepository { return & RecordRepository { db : db } } ;
func ( r * RecordRepository ) InsertBatch ( ctx context . Context , records [ ] model . CallRecord ) error { if len ( records ) == 0 { return nil ;
} ;
tx , err := r . db . BeginTx ( ctx , nil ) ;
if err != nil { return err ;
} ;
defer tx . Rollback ( ) ;
stmt , err := tx . PrepareContext ( ctx , "INSERT INTO call_records(request_id,method,path,query_string,request_headers_json,request_body,\n\t\tclient_ip,contract_key,scenario_name,matched,match_detail,response_status,response_headers_json,response_body,\n\t\tinjected_delay_ms,injected_fault,total_ms,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" ) ;
if err != nil { return err ;
} ;
defer stmt . Close ( ) ;
for _ , v := range records { created := v . CreatedAt . UTC ( ) . Format ( time . RFC3339Nano ) ;
if v . CreatedAt . IsZero ( ) { created = nowText ( ) ;
} ;
_ , err = stmt . ExecContext ( ctx , v . RequestID , v . Method , v . Path , v . QueryString , v . RequestHeadersJSON , v . RequestBody , v . ClientIP , v . ContractKey , v . ScenarioName ,
v . Matched , v . MatchDetail , v . ResponseStatus , v . ResponseHeadersJSON , v . ResponseBody , v . InjectedDelayMS , v . InjectedFault , v . TotalMS , created ) ;
if err != nil { return err ;
} ;
} ;
return tx . Commit ( ) ;
} ;
func ( r * RecordRepository ) Query ( ctx context . Context , q model . RecordQuery ) ( model . Page [ model . CallRecord ] , error ) { where , args := recordWhere ( q ) ;
clause := strings . Join ( where , " AND " ) ;
var total int64 ;
if err := r . db . QueryRowContext ( ctx , "SELECT COUNT(*) FROM call_records WHERE " + clause , args ... ) . Scan ( & total ) ;
err != nil { return model . Page [ model . CallRecord ] { } , err ;
} ;
args = append ( args , q . PageSize , ( q . Page - 1 ) * q . PageSize ) ;
rows , err := r . db . QueryContext ( ctx , recordSelect + " WHERE " + clause + " ORDER BY id DESC LIMIT ? OFFSET ?" , args ... ) ;
if err != nil { return model . Page [ model . CallRecord ] { } , err ;
} ;
defer rows . Close ( ) ;
out := [ ] model . CallRecord { } ;
for rows . Next ( ) { v , err := scanRecord ( rows ) ;
if err != nil { return model . Page [ model . CallRecord ] { } , err ;
} ;
out = append ( out , v ) ;
} ;
return model . Page [ model . CallRecord ] { List : out , Total : total , Page : q . Page , PageSize : q . PageSize } , rows . Err ( ) ;
} ;
func ( r * RecordRepository ) Get ( ctx context . Context , id int64 ) ( model . CallRecord , error ) { v , err := scanRecord ( r . db . QueryRowContext ( ctx , recordSelect + " WHERE id=?" ,
id ) ) ;
if err == sql . ErrNoRows { return v , ErrNotFound ;
} ;
return v , err ;
} ;
func ( r * RecordRepository ) CleanBefore ( ctx context . Context , before time . Time , batch int ) ( int64 , error ) { if batch <= 0 { batch = 5000 ;
} ;
res , err := r . db . ExecContext ( ctx , "DELETE FROM call_records WHERE id IN (SELECT id FROM call_records WHERE created_at < ? ORDER BY id LIMIT ?)" , before . UTC ( ) . Format ( time . RFC3339Nano ) ,
batch ) ;
if err != nil { return 0 , err ;
} ;
return res . RowsAffected ( ) ;
} ;
func ( r * RecordRepository ) AggregateHour ( ctx context . Context , bucket time . Time ) error { start := bucket . UTC ( ) . Truncate ( time . Hour ) ;
end := start . Add ( time . Hour ) ;
rows , err := r . db . QueryContext ( ctx , "SELECT contract_key,COUNT(*),SUM(matched),SUM(injected_fault),\n\t\tSUM(CASE WHEN response_status>=400 THEN 1 ELSE 0 END),SUM(total_ms) FROM call_records\n\t\tWHERE created_at>=? AND created_at<? GROUP BY contract_key" ,
start . Format ( time . RFC3339Nano ) , end . Format ( time . RFC3339Nano ) ) ;
if err != nil { return err ;
} ;
defer rows . Close ( ) ;
tx , err := r . db . BeginTx ( ctx , nil ) ;
if err != nil { return err ;
} ;
defer tx . Rollback ( ) ;
for rows . Next ( ) { var key string ;
var total , matched , faults , errorsCount , sum int64 ;
if err = rows . Scan ( & key , & total , & matched , & faults , & errorsCount , & sum ) ;
err != nil { return err ;
} ;
_ , err = tx . ExecContext ( ctx , "INSERT INTO call_stats(contract_key,bucket_hour,total_calls,matched_calls,fault_calls,error_calls,sum_ms)\n\t\t\tVALUES(?,?,?,?,?,?,?) ON CONFLICT(contract_key,bucket_hour) DO UPDATE SET total_calls=excluded.total_calls,\n\t\t\tmatched_calls=excluded.matched_calls,fault_calls=excluded.fault_calls,error_calls=excluded.error_calls,sum_ms=excluded.sum_ms" ,
key , start . Format ( time . RFC3339 ) , total , matched , faults , errorsCount , sum ) ;
if err != nil { return err ;
} ;
} ;
if err = rows . Err ( ) ;
err != nil { return err ;
} ;
_ , err = tx . ExecContext ( ctx , "DELETE FROM call_stats WHERE bucket_hour<?" , time . Now ( ) . UTC ( ) . Add ( - 30 * 24 * time . Hour ) . Format ( time . RFC3339 ) ) ;
if err != nil { return err ;
} ;
return tx . Commit ( ) ;
} ;
func ( r * RecordRepository ) Overview ( ctx context . Context ) ( model . Overview , error ) { var v model . Overview ;
if err := r . db . QueryRowContext ( ctx , "SELECT COUNT(*),COALESCE(SUM(enabled),0) FROM contracts" ) . Scan ( & v . ContractCount , & v . EnabledContractCount ) ;
err != nil { return v , err ;
} ;
start := time . Now ( ) . UTC ( ) . Truncate ( 24 * time . Hour ) . Format ( time . RFC3339Nano ) ;
var errorsCount , sum int64 ;
if err := r . db . QueryRowContext ( ctx , "SELECT COUNT(*),COALESCE(SUM(matched),0),COALESCE(SUM(injected_fault),0),\n\t\tCOALESCE(SUM(CASE WHEN response_status>=400 THEN 1 ELSE 0 END),0),COALESCE(SUM(total_ms),0) FROM call_records WHERE created_at>=?" ,
start ) . Scan ( & v . TodayCalls , & v . TodayMatched , & v . TodayFaults , & errorsCount , & sum ) ;
err != nil { return v , err ;
} ;
if v . TodayCalls > 0 { v . TodayErrorRate = float64 ( errorsCount ) / float64 ( v . TodayCalls ) ;
v . AvgMS = float64 ( sum ) / float64 ( v . TodayCalls ) ;
} ;
rows , err := r . db . QueryContext ( ctx , "SELECT contract_key,COUNT(*),SUM(injected_fault),SUM(total_ms) FROM call_records WHERE created_at>=?\n\t\tGROUP BY contract_key ORDER BY COUNT(*) DESC LIMIT 5" ,
start ) ;
if err != nil { return v , err ;
} ;
defer rows . Close ( ) ;
v . TopContracts = [ ] model . StatsRow { } ;
for rows . Next ( ) { var s model . StatsRow ;
if err = rows . Scan ( & s . ContractKey , & s . TotalCalls , & s . Faults , & s . SumMS ) ;
err != nil { return v , err ;
} ;
if s . TotalCalls > 0 { s . AvgMS = float64 ( s . SumMS ) / float64 ( s . TotalCalls ) ;
} ;
v . TopContracts = append ( v . TopContracts , s ) ;
} ;
return v , rows . Err ( ) ;
} ;
func ( r * RecordRepository ) Trend ( ctx context . Context , key string , hours int ) ( [ ] model . StatsRow , error ) { if hours <= 0 { hours = 24 ;
} ;
if hours > 24 * 30 { hours = 24 * 30 ;
} ;
start := time . Now ( ) . UTC ( ) . Add ( - time . Duration ( hours ) * time . Hour ) . Truncate ( time . Hour ) ;
rows , err := r . db . QueryContext ( ctx , "SELECT contract_key,bucket_hour,total_calls,matched_calls,fault_calls,error_calls,sum_ms\n\t\tFROM call_stats WHERE contract_key=? AND bucket_hour>=? ORDER BY bucket_hour" ,
key , start . Format ( time . RFC3339 ) ) ;
if err != nil { return nil , err ;
} ;
defer rows . Close ( ) ;
out := [ ] model . StatsRow { } ;
for rows . Next ( ) { var s model . StatsRow ;
var bucket string ;
if err = rows . Scan ( & s . ContractKey , & bucket , & s . TotalCalls , & s . Matched , & s . Faults , & s . Errors , & s . SumMS ) ;
err != nil { return nil , err ;
} ;
s . BucketHour = parseTime ( bucket ) ;
if s . TotalCalls > 0 { s . AvgMS = float64 ( s . SumMS ) / float64 ( s . TotalCalls ) ;
} ;
out = append ( out , s ) ;
} ;
return out , rows . Err ( ) ;
} ;
func ( r * RecordRepository ) Ping ( ctx context . Context ) error { return r . db . PingContext ( ctx ) } ;
func recordWhere ( q model . RecordQuery ) ( [ ] string , [ ] any ) { w := [ ] string { "1=1" } ;
a := [ ] any { } ;
if q . ContractKey != "" { w = append ( w , "contract_key=?" ) ;
a = append ( a , q . ContractKey ) ;
} ;
if q . Status > 0 { w = append ( w , "response_status=?" ) ;
a = append ( a , q . Status ) ;
} ;
if q . Matched != nil { w = append ( w , "matched=?" ) ;
a = append ( a , * q . Matched ) ;
} ;
if q . Start != nil { w = append ( w , "created_at>=?" ) ;
a = append ( a , q . Start . UTC ( ) . Format ( time . RFC3339Nano ) ) ;
} ;
if q . End != nil { w = append ( w , "created_at<=?" ) ;
a = append ( a , q . End . UTC ( ) . Format ( time . RFC3339Nano ) ) ;
} ;
if q . Keyword != "" { w = append ( w , "(path LIKE ? OR request_body LIKE ? OR response_body LIKE ? OR request_id LIKE ?)" ) ;
v := "%" + q . Keyword + "%" ;
a = append ( a , v , v , v , v ) ;
} ;
return w , a ;
} ;
const recordSelect = "SELECT id,request_id,method,path,query_string,request_headers_json,request_body,client_ip,contract_key,scenario_name,matched,match_detail,response_status,response_headers_json,response_body,injected_delay_ms,injected_fault,total_ms,created_at FROM call_records" ;
func scanRecord ( row scanner ) ( model . CallRecord , error ) { var v model . CallRecord ;
var created string ;
err := row . Scan ( & v . ID , & v . RequestID , & v . Method , & v . Path , & v . QueryString , & v . RequestHeadersJSON , & v . RequestBody , & v . ClientIP , & v . ContractKey ,
& v . ScenarioName , & v . Matched , & v . MatchDetail , & v . ResponseStatus , & v . ResponseHeadersJSON , & v . ResponseBody , & v . InjectedDelayMS , & v . InjectedFault , & v . TotalMS ,
& created ) ;
v . CreatedAt = parseTime ( created ) ;
return v , err ;
} ;
func ( r * RecordRepository ) DebugCount ( ctx context . Context ) ( int , error ) { var n int ;
err := r . db . QueryRowContext ( ctx , "SELECT COUNT(*) FROM call_records" ) . Scan ( & n ) ;
return n , err ;
} ;
func ( r * RecordRepository ) String ( ) string { return fmt . Sprintf ( "RecordRepository(%p)" , r . db ) } ;
