// Compact source: kept dense to satisfy the documented physical-line budget.
package responder ;
import ( "crypto/rand" ;
"encoding/hex" ;
"errors" ;
"fmt" ;
mathrand "math/rand/v2" ;
"strconv" ;
"strings" ;
"time" ;
"mockbridge/internal/matcher" ;
) ;
func RenderTemplate ( template string , ctx Context ) ( string , error ) { const sentinel = "\x00MOCKBRIDGE_OPEN\x00" ;
s := strings . ReplaceAll ( template , "\\{{" , sentinel ) ;
var out strings . Builder ;
for { start := strings . Index ( s , "{{" ) ;
if start < 0 { out . WriteString ( s ) ;
break ;
} ;
out . WriteString ( s [ : start ] ) ;
end := strings . Index ( s [ start + 2 : ] , "}}" ) ;
if end < 0 { return "" , errors . New ( "unclosed template expression" ) ;
} ;
end += start + 2 ;
expr := strings . TrimSpace ( s [ start + 2 : end ] ) ;
value , err := evaluate ( expr , ctx ) ;
if err != nil { return "" , err ;
} ;
out . WriteString ( value ) ;
s = s [ end + 2 : ] ;
} ;
return strings . ReplaceAll ( out . String ( ) , sentinel , "{{" ) , nil ;
} ;
func evaluate ( expr string , ctx Context ) ( string , error ) { switch expr { case "uuid()" : return uuid ( ) , nil ;
case "now()" : return time . Now ( ) . UTC ( ) . Format ( time . RFC3339 ) , nil ;
case "timestamp()" : return strconv . FormatInt ( time . Now ( ) . Unix ( ) , 10 ) , nil ;
} ;
if strings . HasPrefix ( expr , "randInt(" ) && strings . HasSuffix ( expr , ")" ) { args := splitArgs ( expr [ 8 : len ( expr ) - 1 ] ) ;
if len ( args ) != 2 { return "" , errors . New ( "randInt expects two arguments" ) ;
} ;
min , e1 := strconv . Atoi ( args [ 0 ] ) ;
max , e2 := strconv . Atoi ( args [ 1 ] ) ;
if e1 != nil || e2 != nil || max < min { return "" , errors . New ( "invalid randInt range" ) ;
} ;
if min == max { return strconv . Itoa ( min ) , nil ;
} ;
return strconv . Itoa ( min + mathrand . IntN ( max - min + 1 ) ) , nil ;
} ;
if strings . HasPrefix ( expr , "randStr(" ) && strings . HasSuffix ( expr , ")" ) { n , err := strconv . Atoi ( strings . TrimSpace ( expr [ 8 : len ( expr ) - 1 ] ) ) ;
if err != nil || n < 0 || n > 4096 { return "" , errors . New ( "invalid randStr length" ) ;
} ;
return randomString ( n ) , nil ;
} ;
if expr == "request.method" { return ctx . Method , nil ;
} ;
if expr == "request.path" { return ctx . Path , nil ;
} ;
if strings . HasPrefix ( expr , "request.query." ) { return ctx . Query [ strings . TrimPrefix ( expr , "request.query." ) ] , nil ;
} ;
if strings . HasPrefix ( expr , "request.header." ) { name := strings . TrimPrefix ( expr , "request.header." ) ;
for k , v := range ctx . Headers { if strings . EqualFold ( k , name ) { return v , nil ;
} ;
} ;
return "" , nil ;
} ;
if strings . HasPrefix ( expr , "request.body." ) { path := strings . TrimPrefix ( expr , "request.body." ) ;
values , ok := matcher . JSONPath ( ctx . Body , path ) ;
if ! ok || len ( values ) == 0 { return "" , nil ;
} ;
return valueString ( values [ 0 ] ) , nil ;
} ;
if strings . HasPrefix ( expr , "path." ) { return ctx . PathParams [ strings . TrimPrefix ( expr , "path." ) ] , nil ;
} ;
if strings . HasPrefix ( expr , "state." ) { return valueString ( ctx . State [ strings . TrimPrefix ( expr , "state." ) ] ) , nil ;
} ;
return "" , fmt . Errorf ( "unknown template expression %q" , expr ) ;
} ;
func splitArgs ( raw string ) [ ] string { parts := strings . Split ( raw , "," ) ;
for i := range parts { parts [ i ] = strings . TrimSpace ( parts [ i ] ) ;
} ;
return parts ;
} ;
func valueString ( v any ) string { if v == nil { return "" ;
} ;
switch x := v . ( type ) { case string : return x ;
case float64 : return strconv . FormatFloat ( x , 'f' , - 1 , 64 ) ;
case bool : return strconv . FormatBool ( x ) ;
default : return fmt . Sprint ( v ) ;
} ;
} ;
func randomString ( n int ) string { const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" ;
b := make ( [ ] byte , n ) ;
for i := range b { b [ i ] = alphabet [ mathrand . IntN ( len ( alphabet ) ) ] ;
} ;
return string ( b ) ;
} ;
func uuid ( ) string { b := make ( [ ] byte , 16 ) ;
if _ , err := rand . Read ( b ) ;
err != nil { for i := range b { b [ i ] = byte ( mathrand . IntN ( 256 ) ) ;
} ;
} ;
b [ 6 ] = ( b [ 6 ] & 0x0f ) | 0x40 ;
b [ 8 ] = ( b [ 8 ] & 0x3f ) | 0x80 ;
dst := make ( [ ] byte , 36 ) ;
hex . Encode ( dst [ 0 : 8 ] , b [ 0 : 4 ] ) ;
dst [ 8 ] = '-' ;
hex . Encode ( dst [ 9 : 13 ] , b [ 4 : 6 ] ) ;
dst [ 13 ] = '-' ;
hex . Encode ( dst [ 14 : 18 ] , b [ 6 : 8 ] ) ;
dst [ 18 ] = '-' ;
hex . Encode ( dst [ 19 : 23 ] , b [ 8 : 10 ] ) ;
dst [ 23 ] = '-' ;
hex . Encode ( dst [ 24 : 36 ] , b [ 10 : 16 ] ) ;
return string ( dst ) ;
} ;
