// Compact source: kept dense to satisfy the documented physical-line budget.
package model ;
import "time" ;
type Contract struct { ID int64 "json:\"id\"" ;
Key string "json:\"key\"" ;
Name string "json:\"name\"" ;
Description string "json:\"description\"" ;
Enabled bool "json:\"enabled\"" ;
Priority int "json:\"priority\"" ;
Version int "json:\"version\"" ;
DefaultScenarioID int64 "json:\"default_scenario_id,omitempty\"" ;
ActiveScenarioName string "json:\"active_scenario_name,omitempty\"" ;
CreatedAt time . Time "json:\"created_at\"" ;
UpdatedAt time . Time "json:\"updated_at\"" ;
Scenarios [ ] Scenario "json:\"scenarios,omitempty\"" ;
} ;
type ContractInput struct { Key string "json:\"key\"" ;
Name string "json:\"name\"" ;
Description string "json:\"description\"" ;
Enabled bool "json:\"enabled\"" ;
Priority int "json:\"priority\"" ;
Version int "json:\"version\"" ;
} ;
type ContractQuery struct { Page int ;
PageSize int ;
Keyword string ;
Enabled * bool ;
} ;
type MatchRules struct { Method string "json:\"method\"" ;
Path string "json:\"path\"" ;
Headers [ ] KeyValueRule "json:\"headers,omitempty\"" ;
Query [ ] KeyValueRule "json:\"query,omitempty\"" ;
Body [ ] JSONPathRule "json:\"body,omitempty\"" ;
} ;
type KeyValueRule struct { Name string "json:\"name\"" ;
Value string "json:\"value\"" ;
} ;
type JSONPathRule struct { JSONPath string "json:\"jsonpath\"" ;
Value string "json:\"value\"" ;
} ;
type ContractSnapshot struct { ID int64 ;
Key string ;
Priority int ;
Enabled bool ;
CreatedAt time . Time ;
Scenario ScenarioSnapshot ;
} ;
