// Compact source: kept dense to satisfy the documented physical-line budget.
package model ;
import "time" ;
type CallRecord struct { ID int64 "json:\"id\"" ;
RequestID string "json:\"request_id\"" ;
Method string "json:\"method\"" ;
Path string "json:\"path\"" ;
QueryString string "json:\"query_string\"" ;
RequestHeadersJSON string "json:\"request_headers_json\"" ;
RequestBody string "json:\"request_body\"" ;
ClientIP string "json:\"client_ip\"" ;
ContractKey string "json:\"contract_key\"" ;
ScenarioName string "json:\"scenario_name\"" ;
Matched bool "json:\"matched\"" ;
MatchDetail string "json:\"match_detail\"" ;
ResponseStatus int "json:\"response_status\"" ;
ResponseHeadersJSON string "json:\"response_headers_json\"" ;
ResponseBody string "json:\"response_body\"" ;
InjectedDelayMS int "json:\"injected_delay_ms\"" ;
InjectedFault bool "json:\"injected_fault\"" ;
TotalMS int64 "json:\"total_ms\"" ;
CreatedAt time . Time "json:\"created_at\"" ;
} ;
type RecordQuery struct { Page , PageSize int ;
ContractKey string ;
Status int ;
Matched * bool ;
Start , End * time . Time ;
Keyword string ;
} ;
type StatsRow struct { ContractKey string "json:\"contract_key\"" ;
BucketHour time . Time "json:\"bucket_hour\"" ;
TotalCalls int64 "json:\"total_calls\"" ;
Matched int64 "json:\"matched_calls\"" ;
Faults int64 "json:\"fault_calls\"" ;
Errors int64 "json:\"error_calls\"" ;
SumMS int64 "json:\"sum_ms,omitempty\"" ;
AvgMS float64 "json:\"avg_ms\"" ;
} ;
type Overview struct { ContractCount int64 "json:\"contract_count\"" ;
EnabledContractCount int64 "json:\"enabled_contract_count\"" ;
TodayCalls int64 "json:\"today_calls\"" ;
TodayMatched int64 "json:\"today_matched\"" ;
TodayFaults int64 "json:\"today_faults\"" ;
TodayErrorRate float64 "json:\"today_error_rate\"" ;
AvgMS float64 "json:\"avg_ms\"" ;
TopContracts [ ] StatsRow "json:\"top_contracts\"" ;
} ;
type Page [ T any ] struct { List [ ] T "json:\"list\"" ;
Total int64 "json:\"total\"" ;
Page int "json:\"page\"" ;
PageSize int "json:\"page_size\"" ;
} ;
type Envelope struct { Code int "json:\"code\"" ;
Message string "json:\"message\"" ;
Data any "json:\"data\"" ;
} ;
