// Compact source: kept dense to satisfy the documented physical-line budget.
package model ;
import "time" ;
type Scenario struct { ID int64 "json:\"id\"" ;
ContractID int64 "json:\"contract_id\"" ;
Name string "json:\"name\"" ;
IsDefault bool "json:\"is_default\"" ;
IsActive bool "json:\"is_active\"" ;
MatchRules MatchRules "json:\"match_rules\"" ;
Response ResponseDef "json:\"response\"" ;
Delay DelayDef "json:\"delay\"" ;
Fault FaultDef "json:\"fault\"" ;
Switch SwitchDef "json:\"switch\"" ;
HitCount int64 "json:\"hit_count\"" ;
CreatedAt time . Time "json:\"created_at\"" ;
UpdatedAt time . Time "json:\"updated_at\"" ;
} ;
type ScenarioInput struct { Name string "json:\"name\"" ;
IsDefault bool "json:\"is_default\"" ;
MatchRules MatchRules "json:\"match_rules\"" ;
Response ResponseDef "json:\"response\"" ;
Delay DelayDef "json:\"delay\"" ;
Fault FaultDef "json:\"fault\"" ;
Switch SwitchDef "json:\"switch\"" ;
} ;
type ResponseDef struct { Status int "json:\"status\"" ;
Headers [ ] KeyValueRule "json:\"headers,omitempty\"" ;
Body string "json:\"body\"" ;
} ;
type DelayDef struct { FixedMS int "json:\"fixed_ms\"" ;
MinMS int "json:\"min_ms\"" ;
MaxMS int "json:\"max_ms\"" ;
} ;
type FaultDef struct { Enabled bool "json:\"enabled\"" ;
Status int "json:\"status\"" ;
Body string "json:\"body\"" ;
Rate float64 "json:\"rate\"" ;
OnCalls [ ] int64 "json:\"on_calls,omitempty\"" ;
} ;
type SwitchDef struct { AfterCalls int64 "json:\"after_calls\"" ;
SwitchToScenario string "json:\"switch_to_scenario,omitempty\"" ;
SwitchToID int64 "json:\"switch_to_scenario_id,omitempty\"" ;
Cron string "json:\"cron\"" ;
} ;
type ScenarioSnapshot struct { ID int64 ;
ContractID int64 ;
Name string ;
Rules MatchRules ;
Response ResponseDef ;
Delay DelayDef ;
Fault FaultDef ;
Switch SwitchDef ;
HitCount int64 ;
} ;
type SwitchResult struct { ContractKey string "json:\"contract_key\"" ;
From string "json:\"from\"" ;
To string "json:\"to\"" ;
Trigger string "json:\"trigger\"" ;
} ;
type SwitchCandidate struct { ContractKey string ;
ScenarioID int64 ;
TargetID int64 ;
Cron string ;
} ;
