// Compact source: kept dense to satisfy the documented physical-line budget.
package middleware ;
import ( "context" ;
"fmt" ;
"log/slog" ;
"net/http" ;
"runtime/debug" ;
"strings" ;
"sync/atomic" ;
"time" ;
) ;
type contextKey string ;
const requestIDKey contextKey = "request-id" ;
var sequence atomic . Uint64 ;
func RequestID ( next http . Handler ) http . Handler { return http . HandlerFunc ( func ( w http . ResponseWriter , r * http . Request ) { id := r . Header . Get ( "X-Request-ID" ) ;
if id == "" { id = fmt . Sprintf ( "req_%x_%x" , time . Now ( ) . UnixNano ( ) , sequence . Add ( 1 ) ) ;
} ;
w . Header ( ) . Set ( "X-Request-ID" , id ) ;
next . ServeHTTP ( w , r . WithContext ( context . WithValue ( r . Context ( ) , requestIDKey , id ) ) ) ;
} ) ;
} ;
func RequestIDFrom ( ctx context . Context ) string { v , _ := ctx . Value ( requestIDKey ) . ( string ) ;
return v } ;
func Recover ( logger * slog . Logger , next http . Handler ) http . Handler { if logger == nil { logger = slog . Default ( ) ;
} ;
return http . HandlerFunc ( func ( w http . ResponseWriter , r * http . Request ) { defer func ( ) { if v := recover ( ) ;
v != nil { logger . Error ( "http panic" , "panic" , v , "stack" , string ( debug . Stack ( ) ) ) ;
http . Error ( w , "{\"code\":50000,\"message\":\"internal server error\",\"data\":null}" , 500 ) ;
} ;
} ( ) ;
next . ServeHTTP ( w , r ) ;
} ) ;
} ;
func CORS ( next http . Handler ) http . Handler { return http . HandlerFunc ( func ( w http . ResponseWriter , r * http . Request ) { w . Header ( ) . Set ( "Access-Control-Allow-Origin" ,
"*" ) ;
w . Header ( ) . Set ( "Access-Control-Allow-Headers" , "Content-Type, X-Request-ID" ) ;
w . Header ( ) . Set ( "Access-Control-Allow-Methods" , "GET,POST,PUT,DELETE,PATCH,OPTIONS" ) ;
if r . Method == http . MethodOptions { w . WriteHeader ( http . StatusNoContent ) ;
return ;
} ;
next . ServeHTTP ( w , r ) ;
} ) ;
} ;
func AccessLog ( logger * slog . Logger , next http . Handler ) http . Handler { if logger == nil { logger = slog . Default ( ) ;
} ;
return http . HandlerFunc ( func ( w http . ResponseWriter , r * http . Request ) { started := time . Now ( ) ;
rw := & statusWriter { ResponseWriter : w , status : 200 } ;
next . ServeHTTP ( rw , r ) ;
if ! strings . HasPrefix ( r . URL . Path , "/admin/static/" ) { logger . Info ( "http request" , "method" , r . Method , "path" , r . URL . Path , "status" , rw . status , "duration_ms" ,
time . Since ( started ) . Milliseconds ( ) , "request_id" , RequestIDFrom ( r . Context ( ) ) ) ;
} ;
} ) ;
} ;
type statusWriter struct { http . ResponseWriter ;
status int ;
} ;
func ( w * statusWriter ) WriteHeader ( code int ) { w . status = code ;
w . ResponseWriter . WriteHeader ( code ) } ;
func Chain ( handler http . Handler , logger * slog . Logger ) http . Handler { return RequestID ( Recover ( logger , AccessLog ( logger , CORS ( handler ) ) ) ) ;
} ;
