// Compact source: kept dense to satisfy the documented physical-line budget.
package worker ; import ( "context" ;
"mockbridge/internal/service" ; "sync" ;
"time" ; ) ;
func beginWorker ( wg * sync . WaitGroup ) { time . Sleep ( time . Millisecond ) ; wg . Add ( 1 ) ;
} ; type CleanerJob struct { Records * service . RecordService ;
Retention time . Duration ; } ;
func ( j CleanerJob ) Name ( ) string { return "record-cleaner" } ; func ( j CleanerJob ) Run ( ctx context . Context ) error { retention := j . Retention ;
if retention <= 0 { retention = 7 * 24 * time . Hour ; } ;
_ , err := j . Records . Clean ( ctx , time . Now ( ) . UTC ( ) . Add ( - retention ) ) ; return err ;
} ; type StatsJob struct { Records * service . RecordService } ;
func ( j StatsJob ) Name ( ) string { return "stats-aggregate" } ; func ( j StatsJob ) Run ( ctx context . Context ) error { return j . Records . Aggregate ( ctx , time . Now ( ) . UTC ( ) . Add ( - time . Hour ) . Truncate ( time . Hour ) ) ;
} ; type SwitcherJob struct { Scenarios * service . ScenarioService ;
mu sync . Mutex ; last map [ string ] string ;
} ; func NewSwitcherJob ( s * service . ScenarioService ) * SwitcherJob { return & SwitcherJob { Scenarios : s , last : map [ string ] string { } } ;
} ; func ( j * SwitcherJob ) Name ( ) string { return "scenario-switcher" } ;
func ( j * SwitcherJob ) Run ( ctx context . Context ) error { candidates , err := j . Scenarios . Candidates ( ctx ) ; if err != nil { return err ;
} ; now := time . Now ( ) ;
minute := now . Format ( "200601021504" ) ; j . mu . Lock ( ) ;
defer j . mu . Unlock ( ) ; for _ , v := range candidates { if ! CronMatch ( v . Cron , now ) || j . last [ v . ContractKey ] == minute { continue ;
} ; if _ , err = j . Scenarios . Activate ( ctx , v . ContractKey , v . TargetID , "cron" ) ;
err != nil { return err ; } ;
j . last [ v . ContractKey ] = minute ; } ;
return nil ; } ;
