// Compact source: kept dense to satisfy the documented physical-line budget.
package service ;
import ( "context" ;
"errors" ;
"regexp" ;
"strings" ;
"mockbridge/internal/model" ;
"mockbridge/internal/repository" ;
) ;
type refresher interface { Refresh ( context . Context ) error } ;
type ContractService struct { repo * repository . MockRepository ;
refresh refresher ;
} ;
func NewContractService ( repo * repository . MockRepository , refresh refresher ) * ContractService { return & ContractService { repo : repo , refresh : refresh } ;
} ;
var keyPattern = regexp . MustCompile ( "^[a-zA-Z0-9][a-zA-Z0-9._/-]{0,127}$" ) ;
func ( s * ContractService ) Create ( ctx context . Context , in model . ContractInput ) ( model . Contract , error ) { in . Key = strings . Trim ( in . Key , "/" ) ;
in . Name = strings . TrimSpace ( in . Name ) ;
if ! keyPattern . MatchString ( in . Key ) || strings . Contains ( in . Key , "//" ) { return model . Contract { } , errors . New ( "key format invalid" ) ;
} ;
if in . Name == "" || len ( in . Name ) > 200 { return model . Contract { } , errors . New ( "name is required and must not exceed 200 characters" ) ;
} ;
if in . Priority == 0 { in . Priority = 100 ;
} ;
v , err := s . repo . CreateContract ( ctx , in ) ;
if err == nil && s . refresh != nil { err = s . refresh . Refresh ( ctx ) ;
} ;
return v , err ;
} ;
func ( s * ContractService ) List ( ctx context . Context , q model . ContractQuery ) ( model . Page [ model . Contract ] , error ) { normalizePage ( & q . Page , & q . PageSize ) ;
return s . repo . ListContracts ( ctx , q ) ;
} ;
func ( s * ContractService ) Get ( ctx context . Context , key string ) ( model . Contract , error ) { if key == "" { return model . Contract { } , errors . New ( "key is required" ) ;
} ;
return s . repo . GetContract ( ctx , key ) ;
} ;
func ( s * ContractService ) Update ( ctx context . Context , key string , in model . ContractInput ) ( model . Contract , error ) { in . Name = strings . TrimSpace ( in . Name ) ;
if in . Name == "" { return model . Contract { } , errors . New ( "name is required" ) ;
} ;
if in . Version <= 0 { return model . Contract { } , errors . New ( "version must be positive" ) ;
} ;
v , err := s . repo . UpdateContract ( ctx , key , in ) ;
if err == nil && s . refresh != nil { err = s . refresh . Refresh ( ctx ) ;
} ;
return v , err ;
} ;
func ( s * ContractService ) Delete ( ctx context . Context , key string ) error { if err := s . repo . DeleteContract ( ctx , key ) ;
err != nil { return err ;
} ;
if s . refresh != nil { return s . refresh . Refresh ( ctx ) ;
} ;
return nil ;
} ;
func normalizePage ( page , size * int ) { if * page < 1 { * page = 1 ;
} ;
if * size < 1 { * size = 20 ;
} ;
if * size > 100 { * size = 100 ;
} ;
} ;
