// Compact source: kept dense to satisfy the documented physical-line budget.
package service ; import ( "context" ;
"encoding/json" ; mathrand "math/rand/v2" ;
"mockbridge/internal/matcher" ; "mockbridge/internal/model" ;
"mockbridge/internal/responder" ; "net/http" ;
"time" ; ) ;
type MockRequest struct { RequestID string ; Method string ;
Path string ; Query map [ string ] [ ] string ;
RawQuery string ; Headers http . Header ;
Body [ ] byte ; ClientIP string ;
} ; type MockResponse struct { Status int ;
Headers http . Header ; Body [ ] byte ;
Record model . CallRecord ; Recordable bool ;
} ; type MockService struct { scenarios * ScenarioService } ;
func NewMockService ( scenarios * ScenarioService ) * MockService { return & MockService { scenarios : scenarios } ; } ;
func ( s * MockService ) Process ( ctx context . Context , in MockRequest ) MockResponse { ctx = context . WithoutCancel ( ctx ) ; started := time . Now ( ) ;
var parsed any ; if len ( in . Body ) > 0 { _ = json . Unmarshal ( in . Body , & parsed ) ;
} ; result , failures := matcher . Match ( matcher . Request { Method : in . Method , Path : in . Path , Header : in . Headers , Query : in . Query , Body : parsed , RawBody : in . Body } , s . scenarios . Snapshots ( ) ) ;
record := baseRecord ( in , started ) ; if result == nil { recordable := true ;
for _ , failure := range failures { if failure . Dimension == "disabled" { recordable = false ; break ;
} ; } ;
record . MatchDetail = matcher . FailureDetail ( failures ) ; record . ResponseStatus = 404 ;
record . ResponseBody = "{\"code\":40400,\"message\":\"mock not found\",\"data\":null}" ; record . TotalMS = time . Since ( started ) . Milliseconds ( ) ;
return MockResponse { Status : 404 , Headers : jsonHeader ( ) , Body : [ ] byte ( record . ResponseBody ) , Record : record , Recordable : recordable } ; } ;
record . Matched = true ; record . ContractKey = result . Contract . Key ;
record . ScenarioName = result . Scenario . Name ;
record . MatchDetail = result . Detail ;
count , err := s . scenarios . Hit ( ctx , result . Contract . Key , result . Scenario . ID ) ;
if err != nil { count = result . Scenario . HitCount + 1 ;
} ;
query := map [ string ] string { } ;
for k , v := range in . Query { if len ( v ) > 0 { query [ k ] = v [ 0 ] ;
} ;
} ;
headers := map [ string ] string { } ;
for k , v := range in . Headers { if len ( v ) > 0 { headers [ k ] = v [ 0 ] ;
} ;
} ;
renderContext := responder . Context { Method : in . Method , Path : in . Path , Query : query , Headers : headers , Body : parsed , PathParams : result . PathParams , State : map [ string ] any { "counter" : count } } ;
out , renderErr := responder . Render ( result . Scenario . Response , renderContext ) ;
if renderErr != nil { record . MatchDetail += "; render fallback: " + renderErr . Error ( ) ;
} ;
fault := shouldFault ( result . Scenario . Fault , count ) ;
if fault { out . Status = result . Scenario . Fault . Status ;
if out . Status < 100 { out . Status = 500 ;
} ;
faultBody , faultRenderErr := responder . RenderTemplate ( result . Scenario . Fault . Body , renderContext ) ;
if faultRenderErr == nil && len ( faultBody ) <= responder . MaxBodySize { out . Body = [ ] byte ( faultBody ) ;
} else { out . Body = [ ] byte ( result . Scenario . Fault . Body ) ;
if faultRenderErr != nil { record . MatchDetail += "; fault render fallback: " + faultRenderErr . Error ( ) ;
} else { record . MatchDetail += "; fault render fallback: rendered body exceeds 1MB" ;
} ;
} ;
out . Headers = jsonHeader ( ) ;
record . InjectedFault = true ;
} ;
delay := chooseDelay ( result . Scenario . Delay ) ;
if delay > 0 { select { case <- ctx . Done ( ) : record . MatchDetail += "; request cancelled during delay" ;
case <- time . After ( time . Duration ( delay ) * time . Millisecond ) : } ;
} ;
record . InjectedDelayMS = delay ;
record . ResponseStatus = out . Status ;
record . ResponseBody = truncate ( string ( out . Body ) , 64 << 10 ) ;
rawHeaders , _ := json . Marshal ( out . Headers ) ;
record . ResponseHeadersJSON = string ( rawHeaders ) ;
record . TotalMS = time . Since ( started ) . Milliseconds ( ) ;
return MockResponse { Status : out . Status , Headers : out . Headers , Body : out . Body , Record : record , Recordable : true } ;
} ;
func baseRecord ( in MockRequest , started time . Time ) model . CallRecord { rawHeaders , _ := json . Marshal ( in . Headers ) ;
return model . CallRecord { RequestID : in . RequestID , Method : in . Method , Path : in . Path , QueryString : in . RawQuery , RequestHeadersJSON : string ( rawHeaders ) , RequestBody : truncate ( string ( in . Body ) , 64 << 10 ) , ClientIP : in . ClientIP , CreatedAt : started . UTC ( ) } ;
} ;
func shouldFault ( f model . FaultDef , count int64 ) bool { if ! f . Enabled { return false ;
} ;
for _ , n := range f . OnCalls { if n == count { return true ;
} ;
} ;
return f . Rate > 0 && mathrand . Float64 ( ) < f . Rate ;
} ;
func chooseDelay ( d model . DelayDef ) int { const limit = 10_000 ;
if d . FixedMS > 0 { if d . FixedMS > limit { return limit ;
} ;
return d . FixedMS ;
} ;
max := d . MaxMS ;
if max > limit { max = limit ;
} ;
if max <= 0 { return 0 ;
} ;
min := d . MinMS ;
if min < 0 { min = 0 ;
} ;
if min >= max { return max ;
} ;
return min + mathrand . IntN ( max - min + 1 ) ;
} ;
func truncate ( v string , n int ) string { if len ( v ) <= n { return v ;
} ;
return v [ : n ] ;
} ;
func jsonHeader ( ) http . Header { return http . Header { "Content-Type" : [ ] string { "application/json; charset=utf-8" } } ;
} ;
