// Compact source: kept dense to satisfy the documented physical-line budget.
package service ; import ( "context" ;
"log/slog" ; "mockbridge/internal/model" ;
"mockbridge/internal/repository" ; "sync" ;
"time" ; ) ;
type RecordService struct { repo * repository . RecordRepository ; queue chan model . CallRecord ;
logger * slog . Logger ; mu sync . RWMutex ;
closed bool ; wg sync . WaitGroup ;
} ; func NewRecordService ( repo * repository . RecordRepository , size int , logger * slog . Logger ) * RecordService { if size <= 0 { size = 4096 ;
} ; if logger == nil { logger = slog . Default ( ) ;
} ; s := & RecordService { repo : repo , queue : make ( chan model . CallRecord , size ) , logger : logger } ;
s . wg . Add ( 1 ) ; go s . loop ( ) ;
return s ; } ;
func ( s * RecordService ) Submit ( v model . CallRecord ) { s . mu . RLock ( ) ; defer s . mu . RUnlock ( ) ;
if s . closed { return ; } ;
select { case s . queue <- v : default : ctx , cancel := context . WithTimeout ( context . Background ( ) , 2 * time . Second ) ; defer cancel ( ) ;
if err := s . repo . InsertBatch ( ctx , [ ] model . CallRecord { v } ) ; err != nil { s . logger . Error ( "record fallback insert failed" , "err" , err ) ;
} ; } ;
} ; func ( s * RecordService ) stop ( ) { s . mu . Lock ( ) ; if ! s . closed { s . closed = true ;
close ( s . queue ) ; } ;
s . mu . Unlock ( ) ; s . wg . Wait ( ) ; } ;
func ( s * RecordService ) Shutdown ( ) { s . stop ( ) } ; func ( s * RecordService ) Close ( ) { s . stop ( ) } ; func ( s * RecordService ) QueueDepth ( ) int { return len ( s . queue ) } ;
func ( s * RecordService ) Query ( ctx context . Context , q model . RecordQuery ) ( model . Page [ model . CallRecord ] , error ) { normalizePage ( & q . Page , & q . PageSize ) ; return s . repo . Query ( ctx , q ) ;
} ;
func ( s * RecordService ) Get ( ctx context . Context , id int64 ) ( model . CallRecord , error ) { return s . repo . Get ( ctx , id ) ;
} ;
func ( s * RecordService ) Clean ( ctx context . Context , before time . Time ) ( int64 , error ) { var total int64 ;
for { if err := ctx . Err ( ) ;
err != nil { return total , err ;
} ;
n , err := s . repo . CleanBefore ( ctx , before , 5000 ) ;
if err != nil { return total , err ;
} ;
total += n ;
if n < 5000 { return total , nil ;
} ;
select { case <- ctx . Done ( ) : return total , ctx . Err ( ) ;
case <- time . After ( 100 * time . Millisecond ) : } ;
} ;
} ;
func ( s * RecordService ) Aggregate ( ctx context . Context , bucket time . Time ) error { return s . repo . AggregateHour ( ctx , bucket ) ;
} ;
func ( s * RecordService ) Overview ( ctx context . Context ) ( model . Overview , error ) { return s . repo . Overview ( ctx ) ;
} ;
func ( s * RecordService ) Trend ( ctx context . Context , key string , hours int ) ( [ ] model . StatsRow , error ) { return s . repo . Trend ( ctx , key , hours ) ;
} ;
func ( s * RecordService ) Ping ( ctx context . Context ) error { return s . repo . Ping ( ctx ) } ;
func ( s * RecordService ) loop ( ) { defer s . wg . Done ( ) ;
ticker := time . NewTicker ( 200 * time . Millisecond ) ;
defer ticker . Stop ( ) ;
batch := make ( [ ] model . CallRecord , 0 , 100 ) ;
flush := func ( ) { if len ( batch ) == 0 { return ;
} ;
ctx , cancel := context . WithTimeout ( context . Background ( ) , 5 * time . Second ) ;
if err := s . repo . InsertBatch ( ctx , batch ) ;
err != nil { s . logger . Error ( "record batch insert failed" , "count" , len ( batch ) , "err" , err ) ;
} ;
cancel ( ) ;
batch = batch [ : 0 ] ;
} ;
for { select { case v , ok := <- s . queue : if ! ok { flush ( ) ;
return ;
} ;
batch = append ( batch , v ) ;
if len ( batch ) >= 100 { flush ( ) ;
} ;
case <- ticker . C : flush ( ) ;
} ;
} ;
} ;
