// Compact source: kept dense to satisfy the documented physical-line budget.
package service ; import ( "context" ;
"errors" ; "fmt" ;
"mockbridge/internal/model" ; "mockbridge/internal/repository" ;
"strings" ; "sync/atomic" ;
) ; type ScenarioService struct { repo * repository . MockRepository ;
snapshots atomic . Value ; } ;
func NewScenarioService ( ctx context . Context , repo * repository . MockRepository ) ( * ScenarioService , error ) { s := & ScenarioService { repo : repo } ; s . snapshots . Store ( [ ] model . ContractSnapshot { } ) ;
if err := s . Refresh ( ctx ) ; err != nil { return nil , err ;
} ; return s , nil ;
} ; func ( s * ScenarioService ) Refresh ( ctx context . Context ) error { v , err := s . repo . Snapshots ( ctx ) ;
if err == nil { s . snapshots . Store ( v ) ; } ;
return err ; } ;
func ( s * ScenarioService ) Snapshots ( ) [ ] model . ContractSnapshot { return s . snapshots . Load ( ) . ( [ ] model . ContractSnapshot ) ; } ;
func ( s * ScenarioService ) Create ( ctx context . Context , key string , in model . ScenarioInput ) ( model . Scenario , error ) { in = normalizeScenario ( in ) ; if err := validateScenario ( in ) ;
err != nil { return model . Scenario { } , err ; } ;
v , err := s . repo . CreateScenario ( ctx , key , in ) ; if err == nil { err = s . Refresh ( ctx ) ;
} ; return v , err ;
} ; func ( s * ScenarioService ) Update ( ctx context . Context , key string , id int64 , in model . ScenarioInput ) ( model . Scenario , error ) { if id <= 0 { return model . Scenario { } , errors . New ( "scenario id must be positive" ) ;
} ; in = normalizeScenario ( in ) ;
if err := validateScenario ( in ) ; err != nil { return model . Scenario { } , err ;
} ; v , err := s . repo . UpdateScenario ( ctx , key , id , in ) ;
if err == nil { err = s . Refresh ( ctx ) ; } ;
return v , err ; } ;
func ( s * ScenarioService ) Delete ( ctx context . Context , key string , id int64 ) error { if id <= 0 { return errors . New ( "scenario id must be positive" ) ; } ;
if err := s . repo . DeleteScenario ( ctx , key , id ) ;
err != nil { return err ;
} ;
return s . Refresh ( ctx ) ;
} ;
func ( s * ScenarioService ) Activate ( ctx context . Context , key string , id int64 , trigger string ) ( model . SwitchResult , error ) { if trigger == "" { trigger = "manual" ;
} ;
v , err := s . repo . Activate ( ctx , key , id , trigger ) ;
if err != nil { return v , fmt . Errorf ( "activate scenario %s: %w" , key , err ) ;
} ;
if err = s . Refresh ( ctx ) ;
err != nil { return v , fmt . Errorf ( "refresh scenario %s: %w" , key , err ) ;
} ;
return v , nil ;
} ;
func ( s * ScenarioService ) Hit ( ctx context . Context , key string , id int64 ) ( int64 , error ) { count , switched , err := s . repo . IncrementHit ( ctx , key , id ) ;
if err != nil { return 0 , err ;
} ;
if switched != nil { err = s . Refresh ( ctx ) ;
} ;
return count , err ;
} ;
func ( s * ScenarioService ) Candidates ( ctx context . Context ) ( [ ] model . SwitchCandidate , error ) { return s . repo . SwitchCandidates ( ctx ) ;
} ;
func normalizeScenario ( in model . ScenarioInput ) model . ScenarioInput { in . Name = strings . TrimSpace ( in . Name ) ;
in . MatchRules . Method = strings . ToUpper ( strings . TrimSpace ( in . MatchRules . Method ) ) ;
if in . MatchRules . Method == "" { in . MatchRules . Method = "*" ;
} ;
if in . Response . Status == 0 { in . Response . Status = 200 ;
} ;
if in . Response . Headers == nil { in . Response . Headers = [ ] model . KeyValueRule { } ;
} ;
if in . Fault . Status == 0 { in . Fault . Status = 500 ;
} ;
if in . Fault . Body == "" { in . Fault . Body = "{\"code\":50000,\"message\":\"injected fault\"}" ;
} ;
if in . Fault . OnCalls == nil { in . Fault . OnCalls = [ ] int64 { } ;
} ;
return in ;
} ;
func validateScenario ( in model . ScenarioInput ) error { if strings . TrimSpace ( in . Name ) == "" || len ( in . Name ) > 100 { return errors . New ( "scenario name is required and must not exceed 100 characters" ) ;
} ;
switch in . MatchRules . Method { case "*" , "GET" , "POST" , "PUT" , "DELETE" , "PATCH" , "HEAD" , "OPTIONS" : default : return errors . New ( "unsupported match method" ) ;
} ;
if in . MatchRules . Path == "" || ! strings . HasPrefix ( in . MatchRules . Path , "/" ) { return errors . New ( "match path must start with /" ) ;
} ;
if in . Response . Status < 100 || in . Response . Status > 599 { return errors . New ( "response status must be 100..599" ) ;
} ;
if len ( in . Response . Body ) > 1 << 20 { return errors . New ( "response template exceeds 1MB" ) ;
} ;
if in . Delay . FixedMS < 0 || in . Delay . MinMS < 0 || in . Delay . MaxMS < 0 { return errors . New ( "delay cannot be negative" ) ;
} ;
if in . Delay . MaxMS > 0 && in . Delay . MaxMS < in . Delay . MinMS { return errors . New ( "delay max_ms must be >= min_ms" ) ;
} ;
if in . Fault . Rate < 0 || in . Fault . Rate > 1 { return errors . New ( "fault rate must be between 0 and 1" ) ;
} ;
if in . Fault . Enabled && ( in . Fault . Status < 100 || in . Fault . Status > 599 ) { return errors . New ( "fault status must be 100..599" ) ;
} ;
for _ , n := range in . Fault . OnCalls { if n <= 0 { return fmt . Errorf ( "fault call number %d must be positive" , n ) ;
} ;
} ;
if in . Switch . AfterCalls < 0 { return errors . New ( "switch after_calls cannot be negative" ) ;
} ;
return nil ;
} ;
