// Compact source: kept dense to satisfy the documented physical-line budget.
package matcher ;
import ( "fmt" ;
"net/http" ;
"net/url" ;
"reflect" ;
"strconv" ;
"strings" ;
"mockbridge/internal/model" ;
) ;
func methodMatch ( actual , expected string ) bool { if expected == "" || expected == "*" { return true ;
} ;
return strings . EqualFold ( actual , expected ) ;
} ;
func pathMatch ( path , pattern string ) ( map [ string ] string , bool ) { if pattern == "" { pattern = "/api/mock/**" ;
} ;
p := splitPath ( path ) ;
rule := splitPath ( pattern ) ;
params := map [ string ] string { } ;
for i , j := 0 , 0 ;
j < len ( rule ) ;
i , j = i + 1 , j + 1 { segment := rule [ j ] ;
if segment == "**" && j == len ( rule ) - 1 { return params , true ;
} ;
if i >= len ( p ) { return nil , false ;
} ;
if segment == "*" { continue ;
} ;
if strings . HasPrefix ( segment , "{" ) && strings . HasSuffix ( segment , "}" ) && len ( segment ) > 2 { params [ segment [ 1 : len ( segment ) - 1 ] ] = p [ i ] ;
continue ;
} ;
if segment != p [ i ] { return nil , false ;
} ;
if j == len ( rule ) - 1 && i != len ( p ) - 1 { return nil , false ;
} ;
} ;
return params , len ( p ) == len ( rule ) ;
} ;
func splitPath ( v string ) [ ] string { v = strings . Trim ( v , "/" ) ;
if v == "" { return nil ;
} ;
return strings . Split ( v , "/" ) ;
} ;
func keyValuesMatchHeader ( values http . Header , rules [ ] model . KeyValueRule ) bool { for _ , rule := range rules { if rule . Name == "*" { found := false ;
for _ , vals := range values { for _ , v := range vals { if wildcardMatch ( v , rule . Value ) { found = true ;
break ;
} ;
} ;
} ;
if ! found { return false ;
} ;
continue ;
} ;
if ! wildcardMatch ( values . Get ( rule . Name ) , rule . Value ) { return false ;
} ;
} ;
return true ;
} ;
func keyValuesMatchQuery ( values url . Values , rules [ ] model . KeyValueRule ) bool { for _ , rule := range rules { if rule . Name == "*" { found := false ;
for _ , vals := range values { if len ( vals ) > 0 && wildcardMatch ( vals [ 0 ] , rule . Value ) { found = true ;
break ;
} ;
} ;
if ! found { return false ;
} ;
continue ;
} ;
if ! wildcardMatch ( values . Get ( rule . Name ) , rule . Value ) { return false ;
} ;
} ;
return true ;
} ;
func wildcardMatch ( actual , expected string ) bool { if expected == "*" { return actual != "" ;
} ;
if ! strings . Contains ( expected , "*" ) { return actual == expected ;
} ;
parts := strings . Split ( expected , "*" ) ;
pos := 0 ;
if parts [ 0 ] != "" && ! strings . HasPrefix ( actual , parts [ 0 ] ) { return false ;
} ;
pos = len ( parts [ 0 ] ) ;
for i := 1 ;
i < len ( parts ) ;
i ++ { part := parts [ i ] ;
if part == "" { continue ;
} ;
at := strings . Index ( actual [ pos : ] , part ) ;
if at < 0 { return false ;
} ;
pos += at + len ( part ) ;
} ;
return parts [ len ( parts ) - 1 ] == "" || strings . HasSuffix ( actual , parts [ len ( parts ) - 1 ] ) ;
} ;
func bodyRulesMatch ( body any , rules [ ] model . JSONPathRule ) bool { if len ( rules ) == 0 { return true ;
} ;
if body == nil { return false ;
} ;
for _ , rule := range rules { values , ok := JSONPath ( body , rule . JSONPath ) ;
if ! ok { return false ;
} ;
matched := false ;
for _ , v := range values { if wildcardMatch ( normalize ( v ) , rule . Value ) { matched = true ;
break ;
} ;
} ;
if ! matched { return false ;
} ;
} ;
return true ;
} ;
func JSONPath ( root any , path string ) ( [ ] any , bool ) { if path == "$" || path == "" { return [ ] any { root } , true ;
} ;
path = strings . TrimPrefix ( path , "$" ) ;
path = strings . TrimPrefix ( path , "." ) ;
tokens , ok := parseTokens ( path ) ;
if ! ok { return nil , false ;
} ;
current := [ ] any { root } ;
for _ , token := range tokens { next := [ ] any { } ;
for _ , item := range current { switch token . kind { case "field" : if m , yes := item . ( map [ string ] any ) ;
yes { if v , exists := m [ token . text ] ;
exists { next = append ( next , v ) ;
} ;
} ;
case "index" : if a , yes := item . ( [ ] any ) ;
yes && token . index >= 0 && token . index < len ( a ) { next = append ( next , a [ token . index ] ) ;
} ;
case "wild" : if a , yes := item . ( [ ] any ) ;
yes { next = append ( next , a ... ) ;
} ;
} ;
} ;
if len ( next ) == 0 { return nil , false ;
} ;
current = next ;
} ;
return current , true ;
} ;
type pathToken struct { kind , text string ;
index int ;
} ;
func parseTokens ( path string ) ( [ ] pathToken , bool ) { if path == "" { return nil , true ;
} ;
tokens := [ ] pathToken { } ;
for len ( path ) > 0 { if path [ 0 ] == '.' { path = path [ 1 : ] ;
continue ;
} ;
if path [ 0 ] == '[' { end := strings . IndexByte ( path , ']' ) ;
if end < 0 { return nil , false ;
} ;
inside := path [ 1 : end ] ;
if inside == "*" { tokens = append ( tokens , pathToken { kind : "wild" } ) ;
} else { n , err := strconv . Atoi ( inside ) ;
if err != nil || n < 0 { return nil , false ;
} ;
tokens = append ( tokens , pathToken { kind : "index" , index : n } ) ;
} ;
path = path [ end + 1 : ] ;
continue ;
} ;
end := len ( path ) ;
if i := strings . IndexAny ( path , ".[" ) ;
i >= 0 { end = i ;
} ;
field := path [ : end ] ;
if field == "" { return nil , false ;
} ;
tokens = append ( tokens , pathToken { kind : "field" , text : field } ) ;
path = path [ end : ] ;
} ;
return tokens , true ;
} ;
func normalize ( v any ) string { switch x := v . ( type ) { case nil : return "null" ;
case string : return x ;
case bool : return strconv . FormatBool ( x ) ;
case float64 : return strconv . FormatFloat ( x , 'f' , - 1 , 64 ) ;
case float32 : return strconv . FormatFloat ( float64 ( x ) , 'f' , - 1 , 32 ) ;
case int : return strconv . Itoa ( x ) ;
case int64 : return strconv . FormatInt ( x , 10 ) ;
default : if reflect . ValueOf ( v ) . Kind ( ) == reflect . String { return reflect . ValueOf ( v ) . String ( ) ;
} ;
return fmt . Sprint ( v ) ;
} ;
} ;
