// Compact source: kept dense to satisfy the documented physical-line budget.
package matcher ; import ( "fmt" ;
"mockbridge/internal/model" ; "net/http" ;
"net/url" ; "sort" ;
"strings" ; ) ;
type Request struct { Method string ; Path string ;
Header http . Header ; Query url . Values ;
Body any ; RawBody [ ] byte ;
} ; type Result struct { Contract model . ContractSnapshot ;
Scenario model . ScenarioSnapshot ; PathParams map [ string ] string ;
Detail string ; } ;
type Failure struct { ContractKey string ; Dimension string ;
} ; func Match ( req Request , contracts [ ] model . ContractSnapshot ) ( * Result , [ ] Failure ) { candidates := append ( [ ] model . ContractSnapshot ( nil ) , contracts ... ) ;
sort . SliceStable ( candidates , func ( i , j int ) bool { if candidates [ i ] . Priority != candidates [ j ] . Priority { return candidates [ i ] . Priority > candidates [ j ] . Priority ; } ;
if ! candidates [ i ] . CreatedAt . Equal ( candidates [ j ] . CreatedAt ) { return candidates [ i ] . CreatedAt . Before ( candidates [ j ] . CreatedAt ) ; } ;
return candidates [ i ] . Key < candidates [ j ] . Key ; } ) ;
failures := [ ] Failure { } ; for _ , c := range candidates { rules := c . Scenario . Rules ;
if ! methodMatch ( req . Method , rules . Method ) { if c . Enabled { failures = append ( failures , Failure { c . Key , "method" } ) ; } ;
continue ; } ;
params , ok := pathMatch ( req . Path , rules . Path ) ; if ! ok { if c . Enabled { failures = append ( failures , Failure { c . Key , "path" } ) ;
} ; continue ;
} ; if ! keyValuesMatchHeader ( req . Header , rules . Headers ) { if c . Enabled { failures = append ( failures , Failure { c . Key , "headers" } ) ;
} ; continue ;
} ; if ! keyValuesMatchQuery ( req . Query , rules . Query ) { if c . Enabled { failures = append ( failures , Failure { c . Key , "query" } ) ;
} ; continue ;
} ;
if ! bodyRulesMatch ( req . Body , rules . Body ) { if c . Enabled { failures = append ( failures , Failure { c . Key , "body" } ) ;
} ;
continue ;
} ;
if ! c . Enabled { failures = append ( failures , Failure { c . Key , "disabled" } ) ;
continue ;
} ;
dims := [ ] string { "method" , "path" } ;
if len ( rules . Headers ) > 0 { dims = append ( dims , "headers" ) ;
} ;
if len ( rules . Query ) > 0 { dims = append ( dims , "query" ) ;
} ;
if len ( rules . Body ) > 0 { dims = append ( dims , "body" ) ;
} ;
return & Result { Contract : c , Scenario : c . Scenario , PathParams : params , Detail : fmt . Sprintf ( "priority=%d matched: %s" , c . Priority , strings . Join ( dims , "," ) ) } , failures ;
} ;
return nil , failures ;
} ;
func FailureDetail ( failures [ ] Failure ) string { if len ( failures ) == 0 { return "no enabled contracts" ;
} ;
limit := len ( failures ) ;
if limit > 8 { limit = 8 ;
} ;
parts := make ( [ ] string , 0 , limit ) ;
for _ , f := range failures [ : limit ] { parts = append ( parts , f . ContractKey + ":" + f . Dimension ) ;
} ;
return "not matched: " + strings . Join ( parts , "," ) ;
} ;
