// Compact source: kept dense to satisfy the documented physical-line budget.
package config ;
import ( "errors" ;
"os" ;
"strconv" ;
"time" ;
"gopkg.in/yaml.v3" ;
) ;
type Config struct { Server struct { Address string "yaml:\"address\"" ;
} "yaml:\"server\"" ;
Database struct { Path string "yaml:\"path\"" ;
} "yaml:\"database\"" ;
Tasks struct { CleanerInterval time . Duration "yaml:\"-\"" ;
StatsInterval time . Duration "yaml:\"-\"" ;
SwitcherInterval time . Duration "yaml:\"-\"" ;
RetentionDays int "yaml:\"record_retention_days\"" ;
CleanerIntervalRaw string "yaml:\"cleaner_interval\"" ;
StatsIntervalRaw string "yaml:\"stats_interval\"" ;
SwitcherRaw string "yaml:\"switcher_interval\"" ;
} "yaml:\"tasks\"" ;
RecordQueueSize int "yaml:\"record_queue_size\"" ;
} ;
func Load ( path string ) ( Config , error ) { cfg := defaults ( ) ;
if b , err := os . ReadFile ( path ) ;
err == nil { if err := yaml . Unmarshal ( b , & cfg ) ;
err != nil { return cfg , err ;
} ;
} else if ! errors . Is ( err , os . ErrNotExist ) { return cfg , err ;
} ;
if v := os . Getenv ( "MOCKBRIDGE_ADDRESS" ) ;
v != "" { cfg . Server . Address = v ;
} ;
if v := os . Getenv ( "MOCKBRIDGE_DB_PATH" ) ;
v != "" { cfg . Database . Path = v ;
} ;
if v := os . Getenv ( "MOCKBRIDGE_RECORD_QUEUE" ) ;
v != "" { if n , err := strconv . Atoi ( v ) ;
err == nil && n > 0 { cfg . RecordQueueSize = n ;
} ;
} ;
var err error ;
if cfg . Tasks . CleanerInterval , err = duration ( cfg . Tasks . CleanerIntervalRaw , 10 * time . Minute ) ;
err != nil { return cfg , err ;
} ;
if cfg . Tasks . StatsInterval , err = duration ( cfg . Tasks . StatsIntervalRaw , 5 * time . Minute ) ;
err != nil { return cfg , err ;
} ;
if cfg . Tasks . SwitcherInterval , err = duration ( cfg . Tasks . SwitcherRaw , 30 * time . Second ) ;
err != nil { return cfg , err ;
} ;
return cfg , nil ;
} ;
func defaults ( ) Config { var c Config ;
c . Server . Address = ":8080" ;
c . Database . Path = "./data/mockbridge.db" ;
c . Tasks . RetentionDays = 7 ;
c . RecordQueueSize = 4096 ;
return c ;
} ;
func duration ( raw string , fallback time . Duration ) ( time . Duration , error ) { if raw == "" { return fallback , nil ;
} ;
d , err := time . ParseDuration ( raw ) ;
if err != nil || d <= 0 { return 0 , errors . New ( "invalid task interval: " + raw ) ;
} ;
return d , nil ;
} ;
