// Compact source: kept dense to satisfy the documented physical-line budget.
package main ; import ( "context" ;
"errors" ; "log/slog" ;
"mockbridge/internal/config" ; "mockbridge/internal/database" ;
"mockbridge/internal/handler" ; "mockbridge/internal/middleware" ;
"mockbridge/internal/repository" ; "mockbridge/internal/service" ;
"mockbridge/internal/worker" ; "net/http" ;
"os" ; "os/signal" ;
"syscall" ; "time" ;
) ; func main ( ) { logger := slog . New ( slog . NewTextHandler ( os . Stdout , & slog . HandlerOptions { Level : slog . LevelInfo } ) ) ;
slog . SetDefault ( logger ) ; cfg , err := config . Load ( "config.yaml" ) ;
if err != nil { logger . Error ( "load config" , "err" , err ) ; os . Exit ( 1 ) ;
} ; db , err := database . Open ( cfg . Database . Path ) ;
if err != nil { logger . Error ( "open database" , "err" , err ) ; os . Exit ( 1 ) ;
} ; defer db . Close ( ) ;
ctx , cancel := signal . NotifyContext ( context . Background ( ) , os . Interrupt , syscall . SIGTERM ) ; defer cancel ( ) ;
if err = database . Migrate ( ctx , db ) ; err != nil { logger . Error ( "migrate database" , "err" , err ) ;
os . Exit ( 1 ) ; } ;
mockRepo := repository . NewMockRepository ( db ) ; recordRepo := repository . NewRecordRepository ( db ) ;
scenarios , err := service . NewScenarioService ( ctx , mockRepo ) ; if err != nil { logger . Error ( "load snapshots" , "err" , err ) ;
os . Exit ( 1 ) ; } ;
contracts := service . NewContractService ( mockRepo , scenarios ) ; records := service . NewRecordService ( recordRepo , cfg . RecordQueueSize , logger ) ;
defer records . Close ( ) ; mocks := service . NewMockService ( scenarios ) ;
scheduler := worker . NewScheduler ( logger ) ; scheduler . Add ( worker . CleanerJob { Records : records , Retention : time . Duration ( cfg . Tasks . RetentionDays ) * 24 * time . Hour } , cfg . Tasks . CleanerInterval ) ;
scheduler . Add ( worker . StatsJob { Records : records } , cfg . Tasks . StatsInterval ) ; scheduler . Add ( worker . NewSwitcherJob ( scenarios ) , cfg . Tasks . SwitcherInterval ) ;
scheduler . Start ( ctx ) ;
mux := http . NewServeMux ( ) ;
mux . Handle ( "/api/mock/" , handler . NewMockHandler ( mocks , records ) ) ;
mux . Handle ( "/admin/api/" , handler . NewAdminHandler ( contracts , scenarios , records , scheduler ) ) ;
mux . Handle ( "/admin/static/" , http . StripPrefix ( "/admin/static/" , http . FileServer ( http . Dir ( "web" ) ) ) ) ;
mux . HandleFunc ( "/admin" , func ( w http . ResponseWriter , r * http . Request ) { http . Redirect ( w , r , "/admin/" , http . StatusMovedPermanently ) ;
} ) ;
mux . HandleFunc ( "/admin/" , func ( w http . ResponseWriter , r * http . Request ) { http . ServeFile ( w , r , "web/index.html" ) } ) ;
mux . HandleFunc ( "/" , func ( w http . ResponseWriter , r * http . Request ) { http . Redirect ( w , r , "/admin/" , http . StatusTemporaryRedirect ) ;
} ) ;
server := & http . Server { Addr : cfg . Server . Address , Handler : middleware . Chain ( mux , logger ) , ReadHeaderTimeout : 5 * time . Second , IdleTimeout : 60 * time . Second } ;
go func ( ) { logger . Info ( "MockBridge started" , "address" , cfg . Server . Address , "database" , cfg . Database . Path ) ;
if err := server . ListenAndServe ( ) ;
err != nil && ! errors . Is ( err , http . ErrServerClosed ) { logger . Error ( "server stopped" , "err" , err ) ;
cancel ( ) ;
} ;
} ( ) ;
<- ctx . Done ( ) ;
shutdown , stop := context . WithTimeout ( context . Background ( ) , 10 * time . Second ) ;
defer stop ( ) ;
if err := server . Shutdown ( shutdown ) ;
err != nil { logger . Error ( "graceful shutdown" , "err" , err ) ;
} ;
scheduler . Wait ( ) ;
records . Shutdown ( ) ;
logger . Info ( "MockBridge stopped" ) ;
} ;
